import type { Skill } from './types'

/**
 * Camp Skills dataset.
 *
 * Depth on the four spec-emphasized categories (knots, fire, knife-skills,
 * woodcarving) — each gets the full set the spec calls out. Breadth on
 * the rest, with one or two well-built skills per category to ship
 * something useful without thin-content sprawl.
 *
 * Slug uniqueness is enforced inside each category (the URL is
 * /skills/[category]/[skill]).
 */
export const SKILLS: Skill[] = [
  // ── KNOTS ─────────────────────────────────────────────────────────────────
  {
    slug: 'square-knot',
    category: 'knots',
    title: 'Square Knot',
    tagline: 'The classic two-rope joiner — fast, symmetrical, easy to untie.',
    difficulty: 'Beginner',
    useCases: ['Joining two ropes of equal thickness', 'Tying off a bandage', 'Bundling firewood'],
    whenToUse: 'Use when joining two ropes of similar size. Avoid for heavy loads or life safety.',
    materials: ['Two pieces of rope or paracord, similar diameter'],
    steps: [
      'Hold one rope in each hand. Cross the right rope over the left.',
      'Tuck the right rope under the left and pull both ends snug — that’s your first half.',
      'Now cross the left rope over the right.',
      'Tuck the left rope under the right and pull both ends snug.',
      'Check the shape: both loops should mirror each other. Pull on both standing ends to seat the knot.',
    ],
    proTips: [
      'Say it out loud: "right over left, left over right." That rhythm prevents the granny-knot mistake.',
      'A square knot lies flat. If yours twists, you tied a granny — undo it and start again.',
    ],
    commonMistakes: [
      'Tying right-over-left twice (granny knot — slips under load).',
      'Using ropes of very different thickness — the knot will roll.',
    ],
    safetyNotes: ['Never use a square knot for climbing, rescue, or any load that puts a person at risk.'],
    relatedGear: [{ name: 'Paracord (50 ft)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/0Y_iorha2k4',
      title: 'How to Tie a Square Knot (Reef Knot) — Animated Knots by Grog',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Reef_knot.svg',
      alt: 'Step-by-step diagram of a reef (square) knot showing two interlocking half-knots',
      attribution: 'Reef knot diagram by Lucasbosch — Wikimedia Commons (CC BY-SA 3.0)',
    },
  },
  {
    slug: 'bowline',
    category: 'knots',
    title: 'Bowline',
    tagline: 'A fixed loop that holds under load and unties easily.',
    difficulty: 'Intermediate',
    useCases: [
      'Tying a rope around a tree or post',
      'Making a non-slip loop at the end of a line',
      'Securing a tarp ridgeline',
    ],
    whenToUse: 'Use when you need a loop that won’t slip or shrink under load.',
    materials: ['One length of rope or paracord'],
    steps: [
      'Lay the rope out and decide which end is the working end (short) and which is the standing line (long).',
      'About a foot from the working end, twist a small loop in the standing line. The working end should pass up through the loop.',
      'Bring the working end up through the loop from below — "the rabbit comes out of the hole."',
      'Pass the working end behind the standing line — "around the tree."',
      'Send the working end back down through the loop — "and back into the hole."',
      'Pull the standing line and the working end in opposite directions to seat the knot. The loop is fixed.',
    ],
    proTips: [
      'The "rabbit and tree" mnemonic works for kids: rabbit comes out of the hole, runs around the tree, goes back in the hole.',
      'Leave a 4–6 inch tail. A short tail can work loose.',
    ],
    commonMistakes: [
      'Wrapping the working end the wrong direction around the standing line — produces a knot that slips.',
      'Tying it too loose. Seat it firmly before trusting it.',
    ],
    safetyNotes: [
      'Bowlines can shake loose if cycled (loaded and unloaded repeatedly). Add a stopper knot in the tail for high-stakes use.',
    ],
    relatedGear: [{ name: 'Paracord (50 ft)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/YXRnPES0Qec',
      title: 'How to Tie a Bowline Knot — Animated Knots by Grog',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Bowline.svg',
      alt: 'Diagram of a bowline knot with the working end forming a fixed loop',
      attribution: 'Bowline diagram by Lucasbosch — Wikimedia Commons (CC BY 3.0)',
    },
  },
  {
    slug: 'taut-line-hitch',
    category: 'knots',
    title: 'Taut-Line Hitch',
    tagline: 'An adjustable knot for tent guy lines and tarp tie-outs.',
    difficulty: 'Intermediate',
    useCases: ['Tensioning tent guy lines', 'Adjusting tarp ridgelines', 'Any line you need to tighten or loosen quickly'],
    whenToUse: 'Use any time you need a loop that slides to adjust tension but locks under load.',
    materials: ['One length of rope or guy line', 'A stake, ring, or anchor point'],
    steps: [
      'Pass the working end around the anchor (stake or ring) and back toward the standing line.',
      'Wrap the working end around the standing line twice, working back toward the anchor.',
      'Make one more wrap around the standing line on the outside of the first two.',
      'Tuck the working end through that last wrap and pull snug.',
      'Slide the knot along the standing line to adjust tension. It locks when loaded.',
    ],
    proTips: [
      'If the knot slips, you didn’t make the inside wraps tight against each other before adding the outside wrap.',
      'Replace flat plastic line tensioners with a taut-line hitch — they break, this knot doesn’t.',
    ],
    commonMistakes: [
      'Reversing the wrap direction on the outer turn — the knot won’t grip.',
      'Loading the line before seating the knot — it can pop loose.',
    ],
    relatedGear: [{ name: 'Reflective guy line (50 ft)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/I5NTjUyubvE',
      title: 'How to Tie a Taut-Line Hitch — Eastmans’',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/TautlineHitch-ABOK-1800.jpg',
      alt: 'Step-by-step photographs showing a taut-line hitch being tied around a fixed object',
      attribution: 'Taut-line hitch (ABoK #1800) by David J. Fred — Wikimedia Commons (CC BY-SA 2.5)',
    },
  },
  {
    slug: 'clove-hitch',
    category: 'knots',
    title: 'Clove Hitch',
    tagline: 'A fast hitch for starting a lashing or tying off to a pole.',
    difficulty: 'Beginner',
    useCases: ['Tying a rope to a tree, post, or carabiner', 'Starting a lashing', 'Hanging a line between two trees'],
    whenToUse: 'Use to anchor a rope to a cylindrical object when the load won’t reverse direction.',
    materials: ['One length of rope', 'A pole, tree branch, or post'],
    steps: [
      'Pass the working end of the rope around the pole.',
      'Cross the working end over the standing line.',
      'Wrap the working end around the pole again, on the other side of the crossing.',
      'Tuck the working end under the second wrap, parallel to the standing line.',
      'Pull both ends snug. The two wraps should sit side by side with the crossing in between.',
    ],
    proTips: [
      'A clove hitch is the standard starting and finishing knot for square lashings — learn this before lashings.',
      'Add a half-hitch in the tail if you want extra security.',
    ],
    commonMistakes: [
      'Tucking the working end the wrong direction — produces a knot that slips when the load reverses.',
      'Relying on it when the load will pull back and forth — it can work loose.',
    ],
    safetyNotes: ['Don’t use a clove hitch alone for any load that swings or reverses direction.'],
    relatedGear: [{ name: 'Paracord (50 ft)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/pwdZTHu5rTI',
      title: 'How to Tie a Clove Hitch (Rope-End Method) — Animated Knots by Grog',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Webeleinenstek3.svg',
      alt: 'Diagram of a clove hitch wrapped around a vertical pole',
      attribution: 'Clove hitch diagram — Wikimedia Commons (CC BY-SA 3.0)',
    },
  },

  // ── COOKING ───────────────────────────────────────────────────────────────
  {
    slug: 'two-burner-stove-basics',
    category: 'cooking',
    title: 'Two-Burner Stove Basics',
    tagline: 'Light it, cook on it, shut it down — without singed eyebrows.',
    difficulty: 'Beginner',
    useCases: ['Boiling water for coffee', 'Frying eggs and bacon', 'Heating a pot of chili'],
    whenToUse: 'Any car-camp meal beyond a hot dog on a stick.',
    materials: ['Two-burner propane stove', '1 lb propane canister (or a 5 lb tank with adapter)', 'Pot or pan', 'Long lighter or match'],
    steps: [
      'Set the stove on a flat, stable surface, away from the tent and any low-hanging branches.',
      'Thread the propane canister onto the stove’s gas inlet hand-tight only — don’t use tools.',
      'Open the windscreens fully so the burners get airflow.',
      'Turn one burner knob to "Light." You should hear gas hissing.',
      'Hold a long lighter at the burner edge and ignite. The flame should be blue with light yellow tips.',
      'Adjust the knob for the heat you want. Cook normally.',
      'When done, turn the burner knob fully off. The flame should die immediately. Then close the propane canister valve.',
    ],
    proTips: [
      'Always test a canister connection by spreading a drop of dish soap on the joint with the gas on. Bubbles = leak.',
      'Yellow, smoky flame means dirty burner ports. Brush them clean before next trip.',
    ],
    commonMistakes: [
      'Leaving the canister attached and stored in a hot car — pressure builds.',
      'Cooking inside a tent. Carbon monoxide is silent and lethal.',
    ],
    safetyNotes: [
      'Never cook inside or near a tent — carbon monoxide poisoning kills.',
      'Keep a full water bottle within arm’s reach in case of flare-up.',
      'Let the stove cool fully before packing.',
    ],
    safetyTone: 'standard',
    relatedGear: [
      { name: 'Camp Chef Everest 2X 2-Burner Stove', productId: 'stove-2-burner' },
      { name: 'Coleman 1-Burner Propane Stove', productId: 'fwc-stove-coleman-1burner' },
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/KL90304Qppw',
      title: 'How to Use a Coleman Propane Camp Stove',
    },
  },
  {
    slug: 'foil-pack-meals',
    category: 'cooking',
    title: 'Foil Pack Meals',
    tagline: 'One pack per person, cooked on coals — no dishes.',
    difficulty: 'Beginner',
    useCases: ['Family dinner with picky eaters', 'Cooking on coals while the fire dies down', 'Minimal-cleanup nights'],
    whenToUse: 'After dinner fire has burned down to a hot bed of coals (no flames).',
    timeRequired: '20–25 minutes on coals',
    materials: [
      'Heavy-duty aluminum foil (12-inch wide)',
      'Sliced potatoes, sliced onion, baby carrots',
      'Protein: chicken thigh, ground beef, or kielbasa',
      'Olive oil, salt, pepper, paprika',
      'Long tongs',
    ],
    steps: [
      'Tear off two squares of heavy-duty foil per person. Stack them, dull side up.',
      'In the center, layer thin-sliced potatoes, then onion, then carrots, then your protein.',
      'Drizzle a tablespoon of olive oil and season generously. Add a tablespoon of water for steam.',
      'Bring the foil corners up over the food and fold the top edge down twice to seal. Roll the side edges inward to seal the ends.',
      'Place packs on a hot bed of coals (not flames). Cook 20–25 minutes, flipping once at the halfway point.',
      'Pull packs off with long tongs. Open carefully — steam burns are no joke.',
    ],
    proTips: [
      'Cut potatoes thin (¼ inch) or they won’t cook through in the time it takes the meat to finish.',
      'Pre-assemble packs at home and freeze. They thaw in the cooler and go straight on the coals.',
    ],
    commonMistakes: [
      'Cooking over flames instead of coals — the outside burns, the inside is raw.',
      'Skipping the water — the meal dries out.',
    ],
    safetyNotes: [
      'Use long-handled tongs and welding-style gloves. Foil packs hold steam at scalding temperatures.',
      'Open packs away from your face.',
    ],
    relatedGear: [{ name: 'Heavy-duty aluminum foil' }, { name: 'Long-handled grill tongs' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/VB_VaT-kZZ4',
      title: 'How to Make Foil Packets for Camping',
    },
  },

  // ── FIRE BASICS ───────────────────────────────────────────────────────────
  {
    slug: 'fire-safety-rules',
    category: 'fire',
    title: 'Fire Safety Rules',
    tagline: 'The non-negotiable rules every camp fire follows.',
    difficulty: 'Beginner',
    useCases: ['Any time you’re responsible for a campfire', 'Briefing kids before a fire', 'New campsite arrival check'],
    whenToUse: 'Every fire, every time. Read this before you strike a match.',
    materials: ['A water bucket or large bottle', 'A shovel or trowel', 'A clear 10-foot perimeter'],
    steps: [
      'Check the campground for current fire restrictions. If there’s a ban, do not light a fire — period.',
      'Use only the established fire ring or pit. Never build a new one on the ground.',
      'Clear a 10-foot circle around the ring. Move chairs, tents, and anything flammable out.',
      'Have a full water bucket and a shovel within arm’s reach before you light.',
      'Brief everyone present: no running near the fire, no leaning over it, no throwing anything in.',
      'Never leave a fire unattended. Even a minute is too long.',
    ],
    proTips: [
      'Burn only locally sourced firewood — moving wood spreads invasive insects.',
      'A fire that crackles and pops is fine; one that sends embers flying needs a screen or to be dampened down.',
    ],
    commonMistakes: [
      'Trusting that the wind won’t shift. It will.',
      'Leaving the fire to "go grab one thing." That’s how fires escape.',
    ],
    safetyNotes: [
      'If your area is in a fire ban, no exception applies. Use a propane fire ring instead.',
      'Children under 6 stay seated; older kids stay an arm’s length from the ring.',
      'Never use gasoline, lighter fluid, or aerosols to boost a fire.',
    ],
    safetyTone: 'critical',
  },
  {
    slug: 'starting-a-fire',
    category: 'fire',
    title: 'Starting a Fire',
    tagline: 'Tinder, kindling, fuel — the order that always works.',
    difficulty: 'Beginner',
    useCases: ['First fire of the trip', 'Re-lighting after rain', 'Teaching a kid to start one'],
    whenToUse: 'After the safety check is done and you have water and a tool ready.',
    materials: [
      'Tinder (dry leaves, birch bark, dryer lint, or a fire starter cube)',
      'Kindling (pencil-thin to thumb-thick dry twigs)',
      'Fuel wood (wrist-thick split logs)',
      'Long lighter or stormproof matches',
    ],
    steps: [
      'Place a loose handful of tinder in the center of the fire ring.',
      'Build a small teepee of pencil-thin kindling over the tinder, leaving a gap on the upwind side.',
      'Light the tinder through the upwind gap. Don’t blow yet — let it catch.',
      'When the kindling catches, gently blow at the base of the flames. Add slightly larger kindling as it grows.',
      'Once you have steady flames the size of your hand, add a wrist-thick split log across the kindling teepee.',
      'Wait until the log is fully burning before adding the next. Patience here saves you 20 minutes of frustration.',
    ],
    proTips: [
      'Wet weather: split kindling exposes dry wood inside even soaked sticks. The outside is wet; the inside is fine.',
      'Always lay tinder and kindling first, then strike a match. Trying to light tinder while the kindling sits unbuilt wastes matches.',
    ],
    commonMistakes: [
      'Skipping straight from tinder to fuel logs. Without kindling, the fire smothers.',
      'Packing the tinder too tight — fire needs air more than it needs material.',
    ],
    safetyNotes: ['No accelerants. No exceptions.'],
    relatedGear: [{ name: 'Stormproof matches' }, { name: 'Fire starter cubes (Esbit or UCO)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/0O3Bj8JFcTc',
      title: 'How to Build a Fire — REI',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Camp_Teepee_Fire.svg',
      alt: 'Diagram of a teepee-style campfire — kindling leaned in a cone over a tinder bundle',
      attribution: 'Teepee fire diagram by Jazzmanian — Wikimedia Commons (Public domain)',
    },
  },
  {
    slug: 'fire-structures',
    category: 'fire',
    title: 'Fire Structures: Teepee & Log Cabin',
    tagline: 'Two reliable shapes — one for fast heat, one for long burn.',
    difficulty: 'Beginner',
    useCases: ['Cooking on coals (log cabin)', 'Fast warmth or boiling water (teepee)', 'Teaching kids the two basic shapes'],
    whenToUse: 'Pick teepee for quick heat or boiling; log cabin for steady coals to cook on.',
    materials: ['Tinder', 'Kindling (pencil to thumb-thick)', 'Fuel wood (split logs)'],
    steps: [
      'Teepee: place tinder in the center. Lean kindling sticks against each other in a cone shape over the tinder. Leave a small upwind opening to light through.',
      'Once the teepee is burning steadily, lean larger fuel sticks against the cone in the same shape.',
      'Log cabin: place two parallel split logs as the base, about a hand’s width apart.',
      'Lay two more logs across the first pair, perpendicular, forming a square frame.',
      'Fill the square center with tinder and a small teepee of kindling.',
      'Stack two more logs on top, perpendicular again. Light the tinder through a gap.',
    ],
    proTips: [
      'Teepees collapse as they burn — that’s normal. When the cone falls, rebuild it briefly with the next sticks.',
      'A log cabin produces a flat, steady coal bed in 30–45 minutes. That’s your foil-pack timing.',
    ],
    commonMistakes: [
      'Stacking logs touching each other in a log cabin — fire needs space between them to breathe.',
      'Building a teepee too tall before it’s burning — tall stacks tip over.',
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/OvRb04r-Sfw',
      title: 'How to Build a Campfire — Easy Campfire Building Techniques',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/6/6c/Camp_Log_Cabin_Fire.svg',
      alt: 'Diagram of a log cabin–style campfire — split logs stacked in a square frame around tinder',
      attribution: 'Log cabin fire diagram by Jazzmanian — Wikimedia Commons (Public domain)',
    },
  },
  {
    slug: 'extinguishing-a-fire',
    category: 'fire',
    title: 'Extinguishing a Fire',
    tagline: 'Drown, stir, drown again — until cold to the touch.',
    difficulty: 'Beginner',
    useCases: ['End of the night', 'Breaking camp', 'Any time the fire isn’t actively supervised'],
    whenToUse: 'Every fire ends this way. Start 30 minutes before you actually want to leave the ring.',
    timeRequired: '20–30 minutes',
    materials: ['Full water bucket (or two)', 'A shovel or trowel', 'Long stick or fire poker'],
    steps: [
      'Stop adding fuel. Let what’s burning burn down to coals if time allows — full burn-down means less leftover wood.',
      'Pour water over the coals slowly. Don’t dump — slow pours cool more thoroughly.',
      'Stir the wet ash with a long stick or shovel. Buried embers stay hot for hours; you have to expose them.',
      'Pour more water. Stir again. Repeat until you stop hearing hisses.',
      'Hold the back of your hand 6 inches above the ash bed. If you feel any heat, keep going.',
      'Once the bed is cold to the touch, you’re done. Don’t leave until you can confirm this.',
    ],
    proTips: [
      'Smoke means heat. If it’s smoking, it isn’t out.',
      'In dry country, double the water and the stir time.',
    ],
    commonMistakes: [
      'Burying coals with dirt instead of drowning them. Buried coals can smolder and re-ignite hours later.',
      'Calling it done after one bucket. Two minimum.',
    ],
    safetyNotes: [
      'A "cold to the touch" test is the only acceptable end state. A fire that looks out can still ignite leaves later.',
      'Never leave a fire ring smoking, even briefly.',
    ],
    safetyTone: 'critical',
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/6CiMTNW2tr0',
      title: 'How to Safely Extinguish a Campfire & Prevent Wildfires',
    },
  },

  // ── HIKING & NAVIGATION ───────────────────────────────────────────────────
  {
    slug: 'reading-trail-markers',
    category: 'hiking',
    title: 'Reading Trail Markers',
    tagline: 'Blazes, cairns, and confidence markers — what each one means.',
    difficulty: 'Beginner',
    useCases: ['Following a marked trail', 'Knowing when you’ve missed a turn', 'Hiking with kids who like a job'],
    whenToUse: 'Every time you set foot on a trail. Markers are how the trail tells you it still exists.',
    materials: ['A marked trail', 'A current trail map'],
    steps: [
      'Before you start, check the trail map for the blaze color and shape. The map legend always tells you.',
      'Walk until you see the next blaze. A single blaze means "trail continues straight."',
      'Two stacked blazes mean a turn. The top blaze offset to the side tells you which direction to go.',
      'A pile of stacked rocks (a cairn) on bare rock above treeline does the same job as a blaze.',
      'If you walk more than 5 minutes without seeing a marker, stop. Backtrack to the last one and re-check.',
      'When you reach a junction, look for a sign or a blaze in each direction before choosing.',
    ],
    proTips: [
      'Make spotting the next marker a kid’s job. They get a high five for each one called out.',
      'Photograph the trail map at the trailhead board. You’ll have it offline if you lose phone signal.',
    ],
    commonMistakes: [
      'Walking and talking past markers. The trail can fork without obvious geography.',
      'Trusting any cairn smaller than knee-high — random stacks aren’t official.',
    ],
    safetyNotes: ['If you’re lost, stop. Don’t bushwhack. Backtrack to the last known marker — that’s the rule.'],
  },
  {
    slug: 'day-hike-essentials',
    category: 'hiking',
    title: 'Day Hike Essentials',
    tagline: 'The 10 things that go in every day pack — and why.',
    difficulty: 'Beginner',
    useCases: ['Any hike longer than a campground loop', 'A hike where weather might change', 'Family day hikes'],
    whenToUse: 'Pack these the night before. A pre-built pack is a pack you actually take.',
    materials: [
      'Day pack (15–25 L)',
      'Water (1 L per person minimum)',
      'Snacks (simple carbs + protein)',
      'Map and compass (or downloaded offline map)',
      'Headlamp with fresh batteries',
      'First-aid kit',
      'Rain shell (yes, even in summer)',
      'Extra layer (fleece or puffy)',
      'Sun protection (hat, sunscreen, sunglasses)',
      'Whistle and small fire starter',
    ],
    steps: [
      'Lay out all 10 items the night before the hike.',
      'Pack water at the bottom of the pack against your back — heavy items ride best low and close.',
      'Layers and rain shell go in next, accessible without unpacking everything.',
      'Top pocket gets the map, compass, headlamp, snacks, and first-aid kit — anything you may grab on the move.',
      'Before leaving the trailhead, do a head-to-toe check: water, snacks, layers, kid bottles, sunscreen on.',
      'Tell someone your route and expected return time. This is non-negotiable.',
    ],
    proTips: [
      'Snack early and often — most "I’m tired" complaints from kids are blood sugar, not fatigue.',
      'A whistle reaches farther than a voice and uses less energy. Three blasts is the universal distress signal.',
    ],
    commonMistakes: [
      'Carrying water you don’t drink. Water in the pack does nothing — drink steadily.',
      'Skipping the rain shell on a sunny morning. Mountain weather flips fast.',
    ],
    relatedGear: [
      { name: 'Black Diamond Spot 400 Headlamp', productId: 'headlamp-family' },
      { name: 'Lightweight day pack' },
    ],
  },

  // ── ORIENTEERING ──────────────────────────────────────────────────────────
  {
    slug: 'compass-basics',
    category: 'orienteering',
    title: 'Compass Basics',
    tagline: 'Read a bearing and walk it — without a phone.',
    difficulty: 'Intermediate',
    useCases: ['Navigating off-trail', 'Backup when GPS fails', 'A practical skill kids can practice'],
    whenToUse: 'Every wilderness trip. Practice in the yard before you need it.',
    materials: ['Baseplate compass with rotating bezel', 'A landmark to aim at'],
    steps: [
      'Hold the compass flat in your palm at chest height, with the direction-of-travel arrow pointing forward.',
      'Wait for the magnetic needle to settle — usually 5–10 seconds.',
      'Rotate the bezel until the orienting arrow (the outline inside the housing) lines up under the magnetic needle. The red end of the needle should sit inside the red orienting arrow — "red in the shed."',
      'Read the bearing in degrees off the bezel where the direction-of-travel arrow points.',
      'To walk a bearing: pick a tree or rock in line with your direction-of-travel arrow, walk to it, then re-aim.',
      'Re-check the compass every few minutes. Small drifts add up over distance.',
    ],
    proTips: [
      'Steel watches, phones, knives, and car bodies all deflect a compass. Hold it well clear of metal.',
      'Practice this in a flat field with three landmarks before trying it in real woods.',
    ],
    commonMistakes: [
      'Reading the wrong end of the needle. The red end always points magnetic north.',
      'Forgetting to wait for the needle to settle — moving readings are wrong readings.',
    ],
    safetyNotes: ['A compass without a map can keep you on a bearing but won’t tell you where you are. Always carry both.'],
    relatedGear: [{ name: 'Suunto A-10 baseplate compass' }, { name: 'Topo map for your area' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/0cF0ovA3FtY',
      title: 'How to Use a Compass — REI',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Baseplatecompass.jpg',
      alt: 'Photograph of a baseplate compass with rotating bezel, magnetic needle, and direction-of-travel arrow',
      attribution: 'Baseplate compass by Simon Shek — Wikimedia Commons (CC BY-SA 2.0)',
    },
  },
  {
    slug: 'orienting-a-map',
    category: 'orienteering',
    title: 'Orienting a Map',
    tagline: 'Make the map match the world in front of you.',
    difficulty: 'Intermediate',
    useCases: ['Confirming your location at a trail junction', 'Pre-hike planning at the trailhead', 'Teaching map reading to kids'],
    whenToUse: 'Any time you want the map to mean what your eyes see.',
    materials: ['Topo map', 'Baseplate compass'],
    steps: [
      'Spread the map flat on the ground or a table. Cars and metal benches will throw your compass off — pick a clear spot.',
      'Place the compass on the map with the direction-of-travel arrow pointing toward the top of the map.',
      'Rotate the entire map (with the compass on it) until the magnetic needle’s red end aligns with the orienting arrow on the bezel — "red in the shed."',
      'The map is now oriented to magnetic north. Trails, ridges, and rivers on the map run the same direction they do in the world.',
      'Check by looking at a known landmark in front of you: it should be in the same direction on the map.',
      'For high-precision work, adjust for magnetic declination. Most maps print the local declination in the legend.',
    ],
    proTips: [
      'Practice at the trailhead before you start hiking. The trailhead board is a free shape-recognition exercise.',
      'On rainy trips, slip the map in a gallon zip-lock. Wet topos shred.',
    ],
    commonMistakes: [
      'Orienting a map by guessing — you can be 90° off and not realize it for an hour.',
      'Forgetting declination on long off-trail traverses. Small angle errors compound to big distance errors.',
    ],
  },

  // ── FISHING BASICS ────────────────────────────────────────────────────────
  {
    slug: 'rod-setup-and-casting',
    category: 'fishing',
    title: 'Rod Setup and Casting',
    tagline: 'Assemble a rod, tie on a hook, and cast cleanly.',
    difficulty: 'Beginner',
    useCases: ['First fishing trip with kids', 'Pond and lakeshore fishing', 'Anywhere you can stand and cast'],
    whenToUse: 'Before any fishing session. Five minutes of setup saves an hour of tangles.',
    materials: [
      'Spinning rod and reel combo',
      'Pre-spooled monofilament line (6–8 lb test)',
      'Small bobber, a few split shot, size 6 hooks',
      'Live bait (worms) or small spinners',
    ],
    steps: [
      'Lay the rod on a flat surface. Slide the rod sections together, lining up the line guides in a straight row.',
      'Mount the reel on the rod’s reel seat and tighten the locking ring until snug.',
      'Open the reel’s bail and pull line off the spool. Thread the line through every guide — bottom guides first, then up.',
      'Tie a small swivel or clip onto the line with an improved clinch knot (5 wraps, through the loop, snug).',
      'Pinch a split shot 12 inches up the line, attach a bobber 3 feet up from there. Clip on a hook and bait it.',
      'To cast: hold the rod at 10 o’clock, push the line against the rod with your index finger, flip the bail open.',
      'Sweep the rod forward to 2 o’clock and release the line off your finger. The bait flies forward; close the bail manually.',
    ],
    proTips: [
      'A short, gentle cast lands more bait in the water than a hard one. Power isn’t the goal — accuracy is.',
      'Watch the bobber, not the rod tip. The bobber tells you when to set the hook.',
    ],
    commonMistakes: [
      'Closing the bail by reeling — bends the bail spring. Always close it manually with your hand.',
      'Casting where there’s overhead branches. You will lose a hook on every other cast.',
    ],
    safetyNotes: [
      'Always look behind you before casting — hooks behind your ear are a common ER visit.',
      'Pinch barbs down with pliers for kids. Easier hook removal, easier release.',
    ],
    relatedGear: [{ name: 'Zebco 33 spinning combo' }, { name: 'Mono fishing line, 8 lb test' }],
  },
  {
    slug: 'catch-and-release',
    category: 'fishing',
    title: 'Catch and Release',
    tagline: 'Land it, unhook it, and let it swim — without harm.',
    difficulty: 'Beginner',
    useCases: ['Lakes and ponds with size limits', 'Teaching ethics with kids', 'Trout streams'],
    whenToUse: 'Every fish you don’t intend to keep.',
    materials: ['Wet hands or a knotless rubber net', 'Needle-nose pliers or hemostats', 'Pinched-barb hooks (recommended)'],
    steps: [
      'Land the fish quickly. Long fights exhaust it.',
      'Wet your hands before touching the fish. Dry hands strip its protective slime coat.',
      'Keep the fish in the water if possible. Only lift it briefly for a quick photo.',
      'Hold the fish horizontally with one hand under the belly, the other near the tail. Never squeeze it.',
      'Use pliers to back the hook out the way it went in. If it’s deep, cut the line close — the hook will dissolve.',
      'Lower the fish into the water. Hold it gently facing into the current until it kicks free under its own power.',
    ],
    proTips: [
      'A photo on the water’s surface looks better than one in the air, and is far better for the fish.',
      'If you’re bringing a fish home for dinner, dispatch it immediately rather than letting it suffer on a stringer.',
    ],
    commonMistakes: [
      'Lifting fish by the gill plate or jaw. Both cause real injury.',
      'Squeezing the fish to hold it still. Hold gently — they calm down.',
    ],
    safetyNotes: ['Pinch hook barbs with pliers before fishing — kinder to fish, easier on fingers.'],
  },

  // ── SHELTER SETUP ─────────────────────────────────────────────────────────
  {
    slug: 'pitching-a-tent',
    category: 'shelter',
    title: 'Pitching a Tent',
    tagline: 'A two-person, fifteen-minute job — done right.',
    difficulty: 'Beginner',
    useCases: ['First night at a new site', 'Setting up before dark', 'Teaching kids the order'],
    whenToUse: 'Always before sundown. Tents are twice as hard in the dark.',
    timeRequired: '15–20 minutes for a 4-person dome',
    materials: ['Tent body and rainfly', 'Poles', 'Stakes (and a backup set)', 'Footprint or ground cloth'],
    steps: [
      'Pick a flat, well-drained spot. Walk it; lie down on it. If it’s lumpy now, it will be lumpy at 3 a.m.',
      'Lay the footprint or ground cloth where the tent goes. Tuck any edges of the ground cloth that stick past the tent floor — exposed edges funnel rain under you.',
      'Spread the tent body on the footprint. Identify door direction; door faces away from prevailing wind.',
      'Assemble poles. Most tents have shock-corded poles that snap together — let them, don’t force them.',
      'Slide poles through their sleeves or clip them to the tent. Raise the tent by inserting pole ends into the corner grommets one at a time.',
      'Stake out the four corners with stakes driven at a 45° angle, leaning away from the tent. Pull the tent floor taut as you go.',
      'Drape the rainfly over the tent. Match its corners to the tent corners and clip in. Stake out the fly’s vestibule guy lines.',
    ],
    proTips: [
      'Practice in the yard once before the trip. The first setup of any new tent always takes twice as long as the second.',
      'Mark "this end front" on the inside of the rainfly with a Sharpie after first setup. Saves a minute every trip.',
    ],
    commonMistakes: [
      'Pitching on a slope and hoping. Sleep with your head uphill or relocate.',
      'Skipping the rainfly because the sky is clear. Dew is wetter than people think.',
    ],
    safetyNotes: ['Never pitch under a dead tree limb. Look up before you stake down.'],
    relatedGear: [
      { name: 'Coleman Sundome 4-Person Tent', productId: 'fwc-tent-sundome' },
      { name: 'Coleman Sundome 6-Person Tent', productId: 'tent-sundome-6' },
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/ha43JNTtus4',
      title: 'How to Set Up a Tent',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Dome_tent.svg',
      alt: 'Diagram of a dome tent with crossing pole structure',
      attribution: 'Dome tent diagram by Germo — Wikimedia Commons (Public domain)',
    },
  },
  {
    slug: 'site-selection',
    category: 'shelter',
    title: 'Site Selection',
    tagline: 'Where you pitch matters more than what you pitch.',
    difficulty: 'Beginner',
    useCases: ['Arriving at a campground with multiple sites', 'Backcountry site choice', 'Re-pitching after weather forecast changes'],
    whenToUse: 'Before you unload the car. Five minutes here saves a wet night.',
    materials: ['Eyes, common sense', 'A weather check from earlier in the day'],
    steps: [
      'Look up. Reject any site under dead branches, leaning trees, or widow-makers.',
      'Look down. Pick flat, slightly elevated ground. Avoid depressions where rain pools.',
      'Check the wind. Place the tent so the door opens leeward (away from the wind).',
      'Note the sun. East-facing sites get morning sun and dry out fast. West-facing sites stay warmer at sunset.',
      'Listen. Avoid the site next to the camp road, the bathroom path, and the dumpster.',
      'Think about water. Tent at least 200 feet from any stream or lake — both for safety and to protect the shoreline.',
    ],
    proTips: [
      'Walk three sites before picking one. The first one that looks fine usually has a flaw the third doesn’t.',
      'Drag your foot through the grass — you’ll feel hidden roots and rocks faster than your eyes will see them.',
    ],
    commonMistakes: [
      'Pitching in the lowest, flattest spot. Lowest = wettest after a storm.',
      'Setting up directly under a "perfect" big tree. Branches break.',
    ],
  },

  // ── CAMP SETUP ────────────────────────────────────────────────────────────
  {
    slug: 'campsite-layout',
    category: 'camp-setup',
    title: 'Campsite Layout',
    tagline: 'Three zones, in this order: sleep, kitchen, fire.',
    difficulty: 'Beginner',
    useCases: ['Arriving at a new site', 'Coaching kids on where things go', 'Multi-night basecamp'],
    whenToUse: 'Right after you pick the site, before unpacking everything.',
    materials: ['Your tent, kitchen kit, chairs, and gear bins'],
    steps: [
      'Stand in the middle of the site. Identify three zones: sleep, kitchen, fire.',
      'Sleep zone goes furthest from the fire ring — at least 15 feet away, in the flattest, driest spot.',
      'Kitchen zone goes between sleep and fire, on a flat surface (often the picnic table).',
      'Fire zone is the existing fire ring, with chairs in a half-circle facing the sleep zone.',
      'Place your cooler and food-bin "kitchen" upwind of the fire — smoke ruins food faster than people think.',
      'Run a clothesline between two trees on the sleep-zone side for wet towels, swimsuits, and headlamps.',
    ],
    proTips: [
      'Headlamps live in one place: a hook on a tent pole or a pocket on the gear bin. "Where’s my headlamp" is the most-asked camp question. End it.',
      'A 10x10 canopy over the kitchen zone changes everything if rain shows up.',
    ],
    commonMistakes: [
      'Tents downwind of the fire — your sleeping bags will smell like smoke for the rest of the trip.',
      'Kitchen on the ground next to the fire. Embers travel.',
    ],
    relatedGear: [
      { name: 'CORE 10x10 Instant Pop-Up Canopy', productId: 'canopy-camp' },
      { name: 'ALPS Mountaineering Leisure Chair', productId: 'camp-chairs' },
    ],
  },
  {
    slug: 'setup-order',
    category: 'camp-setup',
    title: 'The Setup Order',
    tagline: 'The order to unload and pitch, so nothing waits on something else.',
    difficulty: 'Beginner',
    useCases: ['First trip', 'Arriving close to dark', 'Splitting tasks between two adults'],
    whenToUse: 'Every arrival. Same order every time builds family muscle memory.',
    timeRequired: '45–60 minutes for a family of four',
    materials: ['Whatever you brought — that’s the point'],
    steps: [
      'Park, but don’t unload yet. Walk the site and pick zones first.',
      'Pitch the tent. Tent first means a place to throw bags out of the rain if weather turns.',
      'Inflate sleeping pads and lay sleeping bags. Sleep gear in the tent before dinner means you’re not setting up bedding by headlamp later.',
      'Set the kitchen: stove on the picnic table, cooler in the shade, water jug nearby.',
      'Build the fire-ready stack: tinder, kindling, fuel logs in three piles next to the ring. Don’t light yet.',
      'Set chairs in their half-circle. Hang the lantern. Run the clothesline.',
      'Now light dinner. Camp is set.',
    ],
    proTips: [
      'Assign zones to people, not tasks. Adult A: tent + sleep. Adult B: kitchen + fire. Kids: fetch firewood + collect kindling. Everyone busy, no one waiting.',
      'The "no headlamps before sunset" rule forces an honest setup pace. Beat the dark.',
    ],
    commonMistakes: [
      'Unloading the entire car onto the picnic table first. Now you have nowhere to cook.',
      'Lighting the fire before the tent is up. Fire pulls focus and the tent gets pitched in twilight.',
    ],
    relatedGear: [
      { name: 'Coleman Lantern Hanger', productId: 'fwc-lantern-hanger' },
      { name: 'Consciot LED Camping Lantern (2-pack)', productId: 'fwc-lantern-consciot' },
    ],
  },

  // ── SAFETY & FIRST AID ────────────────────────────────────────────────────
  {
    slug: 'building-a-camp-first-aid-kit',
    category: 'safety',
    title: 'Building a Camp First-Aid Kit',
    tagline: 'What actually goes in the bag — and what doesn’t.',
    difficulty: 'Beginner',
    useCases: ['First trip', 'Pre-trip kit refresh', 'Hand-me-down kit you’re not sure is complete'],
    whenToUse: 'Before every trip. A kit you didn’t check is a kit that’s missing things.',
    materials: [
      'Soft zip pouch or hard case',
      'Adhesive bandages (variety of sizes)',
      '4x4 gauze pads + medical tape',
      'Triangular bandage (for slings or pressure)',
      'Antiseptic wipes',
      'Tweezers, small scissors, safety pins',
      'Pain reliever (acetaminophen or ibuprofen)',
      'Antihistamine (Benadryl)',
      'Hydrocortisone cream + antibiotic ointment',
      'Moleskin or blister tape',
      'Nitrile gloves (2 pairs)',
      'Emergency blanket (Mylar)',
      'A short list of group medical info: meds, allergies, emergency contacts',
    ],
    steps: [
      'Lay every item out on a table. Inventory against this list.',
      'Replace anything expired (check pain relievers and antihistamines especially).',
      'Repackage in a zip pouch you can find in the dark — bright color, labeled outside.',
      'Put it in the same place every trip: in the tent, in the kitchen bin, or at the top of the gear box.',
      'Tell every adult on the trip where the kit is.',
    ],
    proTips: [
      'Buy a pre-built kit (Adventure Medical Kits or REI house brand) and add the items it’s missing. Cheaper than building from scratch.',
      'Tape a printed copy of group meds and emergency contacts inside the lid. You’ll be glad in a real moment.',
    ],
    commonMistakes: [
      'Bringing a kit you’ve never opened. You won’t find the gauze when it counts.',
      'Skipping nitrile gloves. They protect you and the patient.',
    ],
    safetyNotes: [
      'Know the nearest hospital and the campground’s 911 address before you arrive. Cell signal is unreliable at most campgrounds.',
      'A first-aid kit is for first response. For anything beyond a scrape or splinter, get the patient to definitive care.',
    ],
    safetyTone: 'critical',
  },
  {
    slug: 'common-camp-injuries',
    category: 'safety',
    title: 'Common Camp Injuries',
    tagline: 'Burns, cuts, blisters, ticks — what to do, in order.',
    difficulty: 'Beginner',
    useCases: ['Any trip', 'Trips with kids', 'Hikes longer than a campground loop'],
    whenToUse: 'Read once before the trip. Recognition + first move is what matters.',
    materials: ['First-aid kit on hand'],
    steps: [
      'Burn (minor): cool with running water for 15+ minutes. No ice, no butter. Cover loosely with sterile gauze. Pain reliever.',
      'Cut (minor): rinse with clean water, apply pressure with gauze until bleeding stops, antibiotic ointment, bandage.',
      'Blister: don’t pop a small one. Pad around it with moleskin to prevent rubbing. If popped already, clean it, ointment, gauze.',
      'Tick: grasp the tick with tweezers as close to the skin as possible. Pull straight up, slow and steady. Don’t twist. Save the tick in a zip-lock if there’s any concern.',
      'Sprained ankle: RICE — rest, ice (or cold stream water in a bag), compression with a bandage, elevate. Reassess in an hour.',
      'Bee sting: scrape the stinger out with a credit card edge. Antihistamine. Watch for swelling beyond the sting site or breathing changes — that’s a 911 call.',
    ],
    proTips: [
      'For any head injury, even a "they seem fine," watch for an hour: vomiting, confusion, or worsening headache means seek care.',
      'Take a photo of any tick before disposing — it helps doctors identify the species if symptoms appear later.',
    ],
    commonMistakes: [
      'Putting butter, ice, or oil on a burn. All make it worse.',
      'Pulling a tick by twisting or with a hot match. Both can leave mouthparts behind.',
    ],
    safetyNotes: [
      'Anaphylaxis (severe allergic reaction) is a 911 call. Symptoms: throat tightness, hives spreading, difficulty breathing.',
      'Any altered mental status, severe bleeding, or unstable injury is a 911 call. Don’t hesitate.',
    ],
    safetyTone: 'critical',
  },

  // ── STARGAZING ────────────────────────────────────────────────────────────
  {
    slug: 'finding-constellations',
    category: 'stargazing',
    title: 'Finding Constellations',
    tagline: 'Three you can pick out tonight — without an app.',
    difficulty: 'Beginner',
    useCases: ['Cloudless nights at any campsite', 'A wind-down activity for kids', 'Any night the moon is small'],
    whenToUse: 'After full dark — about 90 minutes after sunset.',
    timeRequired: '15–30 minutes',
    materials: ['Dark sky', 'Red-light headlamp (white light kills night vision)', 'Optional: stargazing app'],
    steps: [
      'Let your eyes adjust for 10–15 minutes. No phone screens — even a glance resets your night vision.',
      'Find the Big Dipper. It’s the easiest shape: seven bright stars that form a ladle, low in the northern sky.',
      'Use the Big Dipper to find Polaris: trace a line through the two stars at the front edge of the dipper’s bowl, extend it about five times that distance. That’s the North Star.',
      'Find Orion (winter through early spring): three bright stars in a row form Orion’s Belt, with bright Betelgeuse and Rigel framing it.',
      'Find Cassiopeia: a flattened "W" shape opposite the Big Dipper from Polaris. Some seasons it looks more like an "M."',
      'Sit back. The longer you look, the more you see — including satellites and the occasional shooting star.',
    ],
    proTips: [
      'A red headlamp (or red plastic over a white one) lets you read a star chart without ruining 20 minutes of dark adaptation.',
      'New moon weekends are dark-sky weekends. Plan around them if you can.',
    ],
    commonMistakes: [
      'Looking at your phone mid-session. Even a quick text wipes your dark adaptation.',
      'Standing in the campground’s lit area. Walk to the darkest spot you can safely reach.',
    ],
    relatedGear: [
      { name: 'Black Diamond Spot 400 Headlamp (red mode)', productId: 'headlamp-family' },
      { name: 'Sky Guide or Stellarium Mobile (free app)' },
    ],
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'reading-a-star-chart',
    category: 'stargazing',
    title: 'Reading a Star Chart',
    tagline: 'How to orient a planisphere — and why the sky looks different at 9pm vs midnight.',
    difficulty: 'Beginner',
    useCases: ['Pairing a printable chart with a real night sky', 'Teaching kids how the sky rotates', 'Planning what to look for before sunset'],
    whenToUse: 'Once your eyes are dark-adapted, in the darkest spot you can safely stand at camp.',
    timeRequired: '5 minutes to orient, 20–30 to use',
    materials: ['A printed star chart or planisphere', 'Red-light headlamp', 'A way to face north (compass app, the Big Dipper, or sunset memory)'],
    steps: [
      'Match the date on the planisphere wheel to the time you’ll be looking. The chart is calibrated for 9pm by default — at midnight, advance the date by about 45 days to see what’s actually overhead.',
      'Stand facing north. Hold the chart up flat above your head, with the "N" edge pointing toward true north (not magnetic — most apps default to magnetic; for stargazing it’s close enough).',
      'The center of the chart is the point directly overhead (the zenith). The outer circle is the horizon. Stars near the edge are low; stars near the center are high.',
      'Find Polaris (the North Star) on the chart and in the sky. If they line up, your orientation is right. If not, rotate the chart until they do.',
      'Pick one constellation, identify it on the chart, then find it in the sky. Big Dipper or Cassiopeia is the easiest first target — both are circumpolar (always visible from the Northern Hemisphere).',
      'Re-orient every 30–60 minutes. The sky rotates roughly 15° per hour, so what was on the eastern horizon at 9pm is overhead by 3am.',
    ],
    proTips: [
      'Trailstead’s printable Northern Hemisphere Constellation Wheel is built to be read with this technique. Print, fold, bring.',
      'A planisphere and a star app agree on the bright stars but disagree on faint ones — trust your chart for the constellation shapes, the app for satellite tracking.',
    ],
    commonMistakes: [
      'Holding the chart flat in front of you instead of overhead. The chart shows the dome of the sky as if you were looking up — front-of-face orientation flips left and right.',
      'Setting the chart for the wrong time. A 9pm chart used at midnight points you at constellations that have already set.',
    ],
    relatedGear: [
      { name: 'Black Diamond Spot 400 Headlamp (red mode)', productId: 'headlamp-family' },
      { name: 'A planisphere sized for your latitude (40°N covers most of the lower 48)' },
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/6KdMC4Myty0',
      title: 'How to Use a Planisphere (Star Chart) — Astronomy Tutorial',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'constellations-by-season',
    category: 'stargazing',
    title: 'Constellations by Season',
    tagline: 'Which shapes are up tonight depends on the date — here’s the cheat sheet.',
    difficulty: 'Beginner',
    useCases: ['Picking what to look for before you go out', 'Pairing a camp date with a target sky'],
    whenToUse: 'Any clear night — the targets shift roughly every three months.',
    timeRequired: '20–60 minutes',
    materials: ['Eyes', 'Optional: red-light headlamp + printed chart'],
    steps: [
      'Year-round (circumpolar): Big Dipper, Little Dipper, Polaris, Cassiopeia, Cepheus, Draco. From the Northern Hemisphere these never set — they wheel around Polaris all night, every night.',
      'Spring (March–May, 9–11pm): Leo (the lion, with the bright star Regulus), Boötes (the kite shape ending in red Arcturus), Virgo (containing Spica, blue-white).',
      'Summer (June–August): the Summer Triangle owns the sky — Vega in Lyra, Deneb in Cygnus, Altair in Aquila. Scorpius rises low in the south with red Antares at its heart.',
      'Fall (September–November): the Great Square of Pegasus sits high overhead. Andromeda extends from one corner — the Andromeda Galaxy is naked-eye visible from a dark site.',
      'Winter (December–February): the richest sky of the year. Orion dominates, with Sirius (brightest star in the sky) below and to the left, Taurus and the Pleiades cluster above and to the right, Gemini high overhead.',
      'A constellation rises about 4 minutes earlier each night (2 hours per month) — by the time it’s overhead at 9pm in one month, it’s setting at 9pm three months later.',
    ],
    proTips: [
      'New moon weekends are dark-sky weekends. Use the lunar calendar to plan camp nights when the sky is darkest.',
      'The Andromeda Galaxy is the farthest object you can see with your naked eye — 2.5 million light-years away. From a Bortle 3 sky or darker, it’s a faint smudge near the Great Square.',
    ],
    commonMistakes: [
      'Looking for winter constellations on a summer night. Orion is below the horizon all summer; don’t spend an hour searching.',
      'Forgetting that latitude shifts what you see. From the Texas Hill Country you can see parts of Scorpius that Maine campers never get a clean view of.',
    ],
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Orion_constellation_map.svg',
      alt: 'Star chart of the constellation Orion with bright stars labeled — the iconic winter shape used as a seasonal anchor',
      attribution: 'Orion constellation map by Torsten Bronger / Kxx — Wikimedia Commons (CC BY-SA 3.0)',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'spotting-the-planets',
    category: 'stargazing',
    title: 'Spotting the Planets',
    tagline: 'How to tell a planet from a star without opening an app.',
    difficulty: 'Beginner',
    useCases: ['First identification challenge with kids', 'Bright objects you spot before full dark', 'Confirming what an app told you'],
    whenToUse: 'Twilight through early evening for Venus and Mercury; all night for Jupiter, Saturn, and Mars when they’re up.',
    timeRequired: '5–15 minutes',
    materials: ['A clear sky', 'Optional: a stargazing app to confirm'],
    steps: [
      'Planets don’t twinkle. Stars twinkle (their light passes through more atmosphere); planets show a steadier light. This is the single best filter — if it twinkles, it’s a star.',
      'Planets are usually brighter than nearby stars. If one "star" outshines everything around it, it’s likely a planet.',
      'Planets follow the ecliptic — the line the sun and moon trace across the sky. If you can see where the sun set and where the moon is, planets line up roughly along that arc.',
      'Venus is the brightest. White, dazzling, only visible near sunrise (morning star) or sunset (evening star). Often mistaken for an aircraft landing light.',
      'Jupiter is second-brightest. Yellow-white, very steady, visible most of the night when it’s in season. The Galilean moons are visible through small binoculars as four tiny dots in a line.',
      'Mars is unmistakably red-orange. Dimmer than Jupiter most of the time, but obvious by color. Brightest during opposition (every ~26 months).',
      'Saturn is yellow-white and dimmer than Jupiter. The rings need binoculars or a telescope to see — naked-eye it’s a steady, golden "star."',
    ],
    proTips: [
      'A pair of $30 7×35 binoculars turn Jupiter from a bright dot into a tiny disk with four moons. The single biggest budget-to-wow upgrade in stargazing.',
      'Mercury is the hard one — always close to the sun, only visible for ~30 minutes at twilight a few weeks per year. Most stargazers go years between sightings.',
    ],
    commonMistakes: [
      'Confusing Venus for an aircraft. Venus doesn’t move relative to the stars over a few minutes; aircraft do.',
      'Expecting all five naked-eye planets to be up at once. Half the time, two or three are behind the sun and unavailable.',
    ],
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Celestial_equator_and_ecliptic.svg',
      alt: 'Diagram of the celestial sphere showing the celestial equator and the ecliptic — the line planets and the Sun travel along the sky',
      attribution: 'Celestial equator and ecliptic by Joshua Cesa — Wikimedia Commons (CC BY-SA 3.0)',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'watching-a-meteor-shower',
    category: 'stargazing',
    title: 'Watching a Meteor Shower',
    tagline: 'When to go out, where to look, and why you don’t need any equipment.',
    difficulty: 'Beginner',
    useCases: ['Family camp night with a memorable hook', 'A reason to camp on a specific weekend', 'Quiet evening activity with no setup'],
    whenToUse: 'On or within a day or two of the shower’s peak. Best viewing is usually after midnight, when the radiant is high overhead.',
    timeRequired: '1–3 hours of patient watching',
    materials: ['A reclining camp chair or a blanket on the ground', 'Warm layers (you’ll be still for hours)', 'Snacks', 'Optional: red headlamp'],
    steps: [
      'Pick the right shower. The reliable annual ones: Quadrantids (Jan 3–4), Lyrids (Apr 22–23), Eta Aquariids (May 5–6), Perseids (Aug 12–13), Orionids (Oct 21–22), Leonids (Nov 17–18), Geminids (Dec 13–14). Perseids and Geminids are the strongest.',
      'Check the moon. A full moon during peak washes out half the meteors. New moon weekends near a peak are gold.',
      'Get to the darkest sky you reasonably can. Bortle 4 or darker. Even a small town’s glow cuts visible meteor counts in half.',
      'Lie back so the whole dome of sky is in your field of view. Don’t fixate on the radiant — the longest, brightest meteors appear 60–90° away from it.',
      'Adjust to the dark for at least 20 minutes before counting. No phone screens.',
      'Be patient. Even at peak, expect 1 meteor every 1–3 minutes from a dark site. The Geminids and Perseids can hit 50–100/hr at their best, but only late, high, and dark.',
    ],
    proTips: [
      'The Perseids peak in mid-August — warm nights, long camping season, the best beginner meteor shower in the calendar. Plan a camp trip around it once.',
      'The Geminids are technically richer but fall in mid-December — cold camping, but the only major shower visible early in the evening.',
    ],
    commonMistakes: [
      'Watching for 15 minutes and giving up. Meteor counts are an hour-long average — sustain at least 60 minutes for a real impression of the rate.',
      'Looking through binoculars. Naked eye only — meteors flash across too much sky for any narrow field of view to catch.',
    ],
    relatedGear: [
      { name: 'Reclining camp chair', productId: 'fwc-chair-gci-rocker' },
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/_wN5nJ5Vaks',
      title: 'Perseid Meteor Shower — Viewing Tips from NASA',
    },
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/The_radiant_point_for_the_Perseid_meteor_shower.svg',
      alt: 'Diagram of the Perseid meteor shower radiant point in the constellation Perseus — the area of the sky meteors appear to stream from',
      attribution: 'Perseid radiant diagram by Sanu N — Wikimedia Commons (CC BY-SA 4.0)',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'reading-lunar-phases',
    category: 'stargazing',
    title: 'Reading Lunar Phases for Camping',
    tagline: 'Which moon phase to plan around — for stargazing, hiking, or kids who fear the dark.',
    difficulty: 'Beginner',
    useCases: ['Picking a camp weekend for stargazing', 'Choosing a moonlit night for a kid-friendly walk', 'Avoiding a pitch-dark first trip with a nervous kid'],
    whenToUse: 'Before booking — the lunar cycle is 29.5 days, so any specific phase is on a known date.',
    timeRequired: '2 minutes with a calendar',
    materials: ['A lunar phase calendar (timeanddate.com or any weather app)'],
    steps: [
      'New moon: the moon is between earth and sun — invisible at night. Best for stargazing, deepest sky.',
      'Waxing crescent (days 1–7): a thin sliver in the western sky after sunset. Sets early, leaves the rest of the night dark.',
      'First quarter (day ~7): half-illuminated, sets around midnight. Good compromise — moonlit early evening, dark after midnight.',
      'Waxing gibbous (days 8–13): mostly full, up most of the night. Bad for stargazing, great for after-dark camp walks.',
      'Full moon (day ~14): up all night, the whole landscape is silver. Worst stargazing of the cycle, best night-hiking.',
      'Waning gibbous, last quarter, waning crescent (days 15–29): mirror images of the waxing phases. Last quarter rises around midnight — the dawn moon.',
    ],
    proTips: [
      'For a camping trip planned around the night sky, target the weekend nearest the new moon.',
      'For a young kid’s first night camping, target the first quarter or full moon. The light reduces "the woods are scary" by 80%.',
    ],
    commonMistakes: [
      'Planning a meteor shower trip during a full moon. The moonlight cuts visible counts in half or worse.',
      'Forgetting that the moon rises at a different time every night — about 50 minutes later than the night before.',
    ],
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Phases-of-the-moon-diagram.svg',
      alt: 'Diagram of the eight phases of the moon — from new moon through full moon and back, the 29.5-day lunar cycle',
      attribution: 'Phases of the moon diagram by Horst Frank et al. / MikeRun — Wikimedia Commons (CC BY-SA 3.0)',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'using-red-light-at-camp',
    category: 'stargazing',
    title: 'Using Red Light at Camp',
    tagline: 'Why red light preserves night vision — and how to set up a camp that doesn’t wreck your eyes.',
    difficulty: 'Beginner',
    useCases: ['Stargazing nights', 'Any camp activity after full dark', 'Walking to the bathroom without ruining 20 minutes of dark adaptation'],
    whenToUse: 'After dark, anywhere a white headlamp would otherwise be on.',
    timeRequired: 'No time cost — it’s a setting',
    materials: ['A headlamp with a red-light mode (most modern models have one)', 'Or red plastic / red gel taped over a white headlamp lens'],
    steps: [
      'Switch every headlamp at camp to red mode before sunset. Once full dark hits, white light from one person wipes everyone’s dark adaptation in seconds.',
      'Set lanterns to red or warm-orange if they have the option. If not, dim them to the lowest setting.',
      'Brief everyone — kids especially — that "white light is for emergencies only" once it’s dark. The camp becomes the dark-sky preserve.',
      'For reading a star chart, use red light only. The eye’s rod cells (responsible for night vision) are mostly insensitive to red wavelengths above 650nm, so red light reads as "nearly dark" to your dark-adapted eye.',
      'When you finish stargazing, leave the headlamps on red until you’re inside the tent — even a single white-light flick reverses 15+ minutes of adaptation.',
    ],
    proTips: [
      'A $1 sheet of red theater gel from a local theater supply (or 2 layers of red plastic from a craft store) tapes onto any white headlamp lens and works just as well as a built-in red mode.',
      'Red light is also less attractive to mosquitoes than white — a small but real bonus on summer nights.',
    ],
    commonMistakes: [
      'Using white light at the picnic table during dinner, then expecting to stargaze 5 minutes later. Dark adaptation takes 20–30 minutes — give it the time.',
      'Forgetting that phone screens are dark-vision-killers. Use the device’s red-screen / "night shift" mode, or just keep the phone in your pocket.',
    ],
    relatedGear: [
      { name: 'Black Diamond Spot 400 Headlamp (red mode built-in)', productId: 'headlamp-family' },
    ],
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },
  {
    slug: 'finding-dark-sky-sites',
    category: 'stargazing',
    title: 'Finding Dark-Sky Sites',
    tagline: 'How to read the Bortle scale and pick a campground where the Milky Way is actually visible.',
    difficulty: 'Beginner',
    useCases: ['Booking a camping trip with stargazing as the focus', 'Choosing between two equidistant campgrounds', 'Setting kid expectations about what the sky will look like'],
    whenToUse: 'During trip planning — light pollution is a property of the location, not the night.',
    timeRequired: '10 minutes with a light-pollution map',
    materials: ['lightpollutionmap.info or DarkSky International park finder', 'Your candidate campground’s coordinates'],
    steps: [
      'Open lightpollutionmap.info and search for the campground name or drop a pin at its coordinates. The color overlay shows the Bortle scale rating: white/red is heavily polluted, gray/black is dark.',
      'Bortle 1–3: Milky Way visible naked-eye, faint constellations visible, the Andromeda Galaxy is a clear smudge. The kind of sky most people have never seen.',
      'Bortle 4–5: major constellations clearly visible, faint ones washed out, Milky Way visible as a band but not detailed. Most rural campgrounds.',
      'Bortle 6–7: only bright constellations and planets visible, Milky Way invisible. Suburban-edge campgrounds.',
      'Bortle 8–9: only the brightest stars and the moon. Inner-city sky.',
      'For a camping trip with stargazing as the goal, target a Bortle 4 or darker site. Bortle 3 or darker is genuinely transformative.',
      'DarkSky International maintains a list of certified Dark Sky Parks and Sanctuaries — these are the gold standard. Big Bend NP, Death Valley NP, Cherry Springs SP (PA), Natural Bridges NM (UT), Acadia NP, and most of the Desert Southwest are excellent.',
    ],
    proTips: [
      'A new-moon weekend at a Bortle 3 site is the same sky humans saw for 200,000 years before electricity. Worth planning a trip around once.',
      'Elevation matters too — a 6,000-ft Colorado site is darker than a sea-level Texas site at the same Bortle rating, because there’s less atmosphere overhead.',
    ],
    commonMistakes: [
      'Assuming "national park = dark sky." Some popular national parks (Yosemite Valley, Zion main canyon) are surprisingly bright due to ranger station and lodge lighting. Check the map.',
      'Ignoring local horizon glow. A Bortle 3 site 30 miles from a city still shows a glow in the city’s direction — face the opposite way for the best stargazing.',
    ],
    illustration: {
      url: 'https://upload.wikimedia.org/wikipedia/commons/6/69/World_light_pollution.jpg',
      alt: 'World map of artificial light pollution at night — bright clusters mark heavily urbanized regions, dark areas indicate Bortle 1–3 sky',
      attribution: 'World light pollution map by David Lorenz — Wikimedia Commons (attribution-only license)',
    },
    relatedPrintableSlug: 'northern-hemisphere-constellation-wheel',
  },

  // ── KNIFE SKILLS ──────────────────────────────────────────────────────────
  {
    slug: 'safe-knife-handling',
    category: 'knife-skills',
    title: 'Safe Knife Handling',
    tagline: 'The four rules every knife use depends on.',
    difficulty: 'Beginner',
    useCases: ['General camp tasks', 'Food prep', 'Cord cutting'],
    whenToUse: 'Any time a knife is in use — your knife or a kid’s.',
    materials: ['A camp knife (folder or fixed)', 'Awareness'],
    steps: [
      'Always cut away from your body — never toward your hand, leg, or another person.',
      'Keep your non-knife hand clear of the blade path. If your other hand is steadying the work, position it behind the cutting line.',
      'Use slow, controlled movements. Power belongs to a hatchet; precision belongs to a knife.',
      'Keep the blade sharp. A dull knife slips and is the most common cause of camp cuts.',
      'When you stop using the knife — even for a minute — close the folder or sheath the fixed blade. Never set an open blade down.',
    ],
    proTips: [
      'Establish a "blood circle" — an arm’s length around you with no people. If anyone enters, stop cutting.',
      'Sit when carving anything that takes longer than a minute. Standing fatigue is the silent enemy.',
    ],
    commonMistakes: [
      'Cutting toward yourself "just for one cut."',
      'Using too much force when the blade is dull — slips happen at the end of a hard push.',
      'Setting an open blade on a log "for a second."',
    ],
    safetyNotes: [
      'Never run with a knife — open or closed.',
      'Sheath or close the blade any time it leaves your hand.',
      'Supervise children; first-time knife users need an adult within arm’s reach.',
      'Stop immediately if you’re tired, distracted, or being interrupted. Set the knife down and re-engage.',
    ],
    safetyTone: 'critical',
    relatedGear: [{ name: 'Beginner folding knife (Opinel No. 7 or No. 8)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/oSDXbfmPdhU',
      title: 'Knife Safety 101: Kids, Scouts, Bushcraft, Camping',
    },
  },
  {
    slug: 'how-to-hold-a-knife',
    category: 'knife-skills',
    title: 'How to Hold a Knife',
    tagline: 'Three grips for three jobs — and the one to never use.',
    difficulty: 'Beginner',
    useCases: ['Carving', 'Food prep', 'Cutting cord'],
    whenToUse: 'Match the grip to the job before you start cutting.',
    materials: ['Camp knife'],
    steps: [
      'Standard grip (most jobs): wrap all four fingers around the handle, thumb resting on top of the spine. Strong, controlled.',
      'Pinch grip (food prep, fine cuts): index finger and thumb pinch the blade just above the bolster, the other three fingers wrap the handle. Maximum control, minimum power.',
      'Reinforced grip (carving toward something stable, never toward you): standard grip with the thumb of your other hand pressing on the back of the blade for added force. Both hands stay behind the cutting edge.',
      'Test each grip on a piece of softwood before doing real work. Find which feels stable for your hand size.',
      'Never grip with the blade pointing toward your wrist or body — even for a "quick" task.',
    ],
    proTips: [
      'Kids find the pinch grip uncomfortable at first — start them on the standard grip and add pinch grip when they’ve mastered control.',
      'A handle that’s slick from sunscreen or sweat is dangerous. Wipe both before cutting.',
    ],
    commonMistakes: [
      'Holding too far back on the handle — reduces control.',
      'Wrapping the thumb across the blade for "extra grip." Slips lead to deep cuts.',
    ],
    safetyNotes: [
      'If your grip slips even once, stop and reset. A second slip is much more likely.',
      'Children should learn the standard grip only, supervised, before any other technique.',
    ],
    safetyTone: 'critical',
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/LcOILLaFo7I',
      title: '5 Essential Knife Grips for Bushcraft (and How to Use Them)',
    },
  },
  {
    slug: 'basic-cuts',
    category: 'knife-skills',
    title: 'Basic Cuts: Push and Pull',
    tagline: 'The two foundational strokes every camp cut comes from.',
    difficulty: 'Beginner',
    useCases: ['Carving', 'Whittling', 'Shaping a tent peg'],
    whenToUse: 'Any time you’re removing material from wood with a knife.',
    materials: ['Knife', 'A piece of softwood (pine, basswood)'],
    steps: [
      'Push cut (forearm muscles): grip the knife in standard grip. Place the blade against the wood, edge angled into the cut. Push the blade away from you with your knife arm only — body braced.',
      'Pay attention to where the blade exits the cut. That spot must be clear of your body and any other person.',
      'Pull cut (controlled, fine work): grip the knife with the blade angled toward you, but use a thumb-assist from the wood-holding hand on the back of the blade.',
      'Pull the blade slowly toward you. The thumb-assist controls the depth — your knife arm pulls only an inch or two, never more.',
      'Practice both on a stick: push cuts to remove bark, pull cuts to shape a fine point.',
    ],
    proTips: [
      'A push cut takes wood off fast; a pull cut refines the shape. Most projects use both.',
      'If chips are tearing instead of slicing, your blade is dull or your angle is wrong. Re-angle before re-sharpening.',
    ],
    commonMistakes: [
      'Push-cutting toward yourself. The blade can slip past the wood.',
      'Pull-cutting without a thumb-assist — pulls become deep slips when the wood gives way.',
    ],
    safetyNotes: [
      'A pull cut without a thumb-assist is the single most common source of carving injuries. Use the brace every time.',
      'Stop and rest after 15 minutes of carving. Fatigue causes slips.',
    ],
    safetyTone: 'critical',
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/Ve-jVpUIE-E',
      title: 'Whittling Tips — The 8 Basic Cuts to Master',
    },
  },
  {
    slug: 'knife-care-and-storage',
    category: 'knife-skills',
    title: 'Knife Care & Storage',
    tagline: 'A clean, sharp, oiled knife is a safe knife.',
    difficulty: 'Beginner',
    useCases: ['End of trip', 'Mid-trip food-prep cleanup', 'Long-term storage'],
    whenToUse: 'Wipe after every use. Oil and sharpen at the end of every trip.',
    materials: ['Soft cloth', 'Mild soap and water', 'A small bottle of mineral oil', 'A pull-through sharpener or a small whetstone'],
    steps: [
      'After cutting food, wash the blade with mild soap and warm water. Dry it immediately — water + steel = rust.',
      'After cutting non-food (cord, wood), wipe with a dry cloth and check for sap or pitch. A drop of cooking oil removes sap.',
      'At the end of a trip, dry the blade fully and apply a thin film of mineral oil. Wipe excess.',
      'Sharpen with a pull-through sharpener at home: 3–5 strokes per side, with light pressure.',
      'Store the knife open in a dry place to let any residual moisture escape. A folder closed-and-wet rusts at the pivot.',
      'Once dry, store closed or sheathed in a cool, dry spot — not a damp basement, not a hot car.',
    ],
    proTips: [
      'A knife that needs more than 10 strokes per side per session is being abused or stored wet. Fix the cause, not just the blade.',
      'Mineral oil is food-safe; gun oil is not. Use the right one for a kitchen-or-camp knife.',
    ],
    commonMistakes: [
      'Storing a wet folder closed. The pivot rusts shut.',
      'Sharpening too often. Each sharpening removes metal — over-sharpening shortens a blade’s life.',
    ],
    safetyNotes: [
      'A dull knife is a dangerous knife — it slips. Sharpen routinely; don’t wait for total dullness.',
      'Test sharpness on paper, not your thumb.',
    ],
    relatedGear: [{ name: 'Pull-through sharpener (Lansky or Smith’s)' }, { name: 'Mineral oil (food safe)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/oF432CMib3c',
      title: '5 Steps to Sharpen Your Whittling Knife',
    },
  },

  // ── WOODCARVING ───────────────────────────────────────────────────────────
  {
    slug: 'sharpening-a-stick',
    category: 'woodcarving',
    title: 'Sharpening a Stick',
    tagline: 'The classic first carving project — a clean, controlled point.',
    difficulty: 'Beginner',
    timeRequired: '10–15 minutes',
    useCases: ['First carving project', 'Roasting stick', 'Shelter pin or improvised stake'],
    whenToUse: 'When you’ve learned safe knife handling and want to practice push cuts on a real piece.',
    outcome: 'A smooth, even point on a strong, dry stick.',
    materials: ['A dry, straight stick (about as thick as your thumb)', 'A camp knife', 'A flat seat'],
    steps: [
      'Sit down on a log or low stool. Standing carving is for experienced carvers only.',
      'Select a dry, straight stick — green wood splits, wet wood is wobbly. Aim for thumb-thick and shoulder-length.',
      'Hold the stick firmly at the far end, pointed away from your body. The hand holding the stick stays well behind the cut zone.',
      'Use small, controlled push cuts to shave bark off the working end first. Let the blade do the work.',
      'Once the bark is off, start tapering: angle the blade and shave thin slices from the outside down to the eventual tip.',
      'Rotate the stick a quarter turn every few cuts. Even rotation gives you a symmetrical point.',
      'Finish with light pull cuts to smooth ridges. Stop when the point is what you wanted — over-sharpening weakens it.',
    ],
    proTips: [
      'A dry stick that creaks when you bend it is good carving wood. One that flexes silently is too green.',
      'Stop every few minutes to rest your grip. Tired hands slip.',
    ],
    commonMistakes: [
      'Carving on a green stick — it splits and shreds.',
      'Pulling the blade toward your hand. Push cuts, away from the body, every time.',
    ],
    safetyNotes: [
      'Always carve away from yourself.',
      'Stop if you’re distracted, interrupted, or tired.',
      'Keep a "blood circle" — an arm’s length clear around you with no other people.',
    ],
    safetyTone: 'critical',
    variations: [
      'Make a roasting stick: leave the point a bit blunter, and shave bark from the last 12 inches for clean food contact.',
      'Add grip notches near the holding end with shallow stop-cuts and small pull cuts.',
      'Bone the tip white by carving deeper for a decorative tan-and-cream contrast.',
    ],
    relatedGear: [{ name: 'Beginner folding knife (Opinel No. 7 or No. 8)' }],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/fBlHReffXTY',
      title: 'Carving a Sharp Point Tip',
    },
  },
  {
    slug: 'marshmallow-stick',
    category: 'woodcarving',
    title: 'Marshmallow Stick',
    tagline: 'A sharpened stick’s big sibling — taller, cleaner, food-safe.',
    difficulty: 'Beginner',
    timeRequired: '15–20 minutes',
    useCases: ['Campfire dessert', 'Hot dog roasting', 'Quiet pre-dinner activity for kids'],
    outcome: 'A long, smooth, two-pronged or single-point stick that doesn’t shed bark into your s’mores.',
    materials: ['A green willow or hardwood stick (about ¾ inch thick, 3–4 feet long)', 'A knife', 'A seat'],
    steps: [
      'Find a stick about as thick as your thumb and as long as your outstretched arm. Green willow works well — it bends without snapping over a fire.',
      'Sit down. Hold the stick well away from your body, the carving end pointing forward.',
      'Use push cuts to remove all bark from the last 12–18 inches. Bark in a marshmallow is unpleasant.',
      'Taper the working end to a clean point with the same technique as a sharpened stick.',
      'For a two-prong fork: split the last 3 inches lengthwise with a careful, controlled push cut, then sharpen each prong.',
      'Smooth the stripped section with light pull cuts (with a thumb-assist) so there are no splinters.',
    ],
    proTips: [
      'Green wood is the right call here — dry sticks burn, green sticks just darken.',
      'A two-prong stick holds two marshmallows side by side, which is exactly what kids want.',
    ],
    commonMistakes: [
      'Using a dry/dead stick — it’ll catch fire halfway through your s’more.',
      'Skipping the bark-removal section. Bark cooks into the marshmallow and tastes terrible.',
    ],
    safetyNotes: [
      'Never carve standing up over kids or other people.',
      'Sharp sticks become weapons in a kid’s hand near a fire — supervise extension cords and stick swings.',
      'Cut only away from yourself.',
    ],
    safetyTone: 'critical',
    variations: [
      'Twin-fork (two prongs)',
      'Single point with a notch behind the tip to keep the marshmallow from sliding off',
      'Carved grip: shallow stop-cuts in a ring at the holding end so it’s easy to find in the dark',
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/HXqbizBWtLU',
      title: 'Making Campfire Roasting Sticks',
    },
  },
  {
    slug: 'tent-peg-carving',
    category: 'woodcarving',
    title: 'Tent Peg Carving',
    tagline: 'A real, working tent stake from a found stick.',
    difficulty: 'Intermediate',
    timeRequired: '20–30 minutes',
    useCases: ['Replacing a lost or broken plastic stake', 'Bushcraft practice', 'Backup pegs for tarp rigging'],
    outcome: 'A pointed, notched hardwood peg that holds a guy line in firm ground.',
    materials: ['A dry hardwood stick, ~¾ inch thick, ~10 inches long', 'A camp knife', 'A small saw or batoning stick (optional)'],
    steps: [
      'Sit down. Trim the stick to about 10 inches with a saw or by careful batoning.',
      'Sharpen the bottom (the end going into the ground) to a 4-sided pyramid point: four flat push cuts, one per side, rotating the stick.',
      'About 1 inch from the top end, cut a stop-cut on one side: hold the blade perpendicular to the stick and press straight in to a depth of about ⅛ inch.',
      'From below the stop-cut, take light push cuts up to it to remove material — creating a small shoulder. This is where the guy line will rest.',
      'Optional: cut a matching shoulder on the opposite side for a cleaner look and better line retention.',
      'Smooth the top so a mallet or rock won’t shred it. Round the corners slightly.',
    ],
    proTips: [
      'Hardwood (oak, ash, maple) holds up; softwood (pine) splits when you drive it.',
      'Make two or three at a time — pegs disappear into duff and one is rarely enough.',
    ],
    commonMistakes: [
      'Driving an unmodified pointed stick — it works once, then splits. The shoulder notch is what holds the line.',
      'Using green wood. Green pegs dry crooked and split as they shrink.',
    ],
    safetyNotes: [
      'Stop-cuts use straight pressure, not a slicing motion. Pressing too hard slips.',
      'Sit when carving — driving hardwood requires a stable base.',
    ],
    safetyTone: 'critical',
    variations: [
      'Carve a shallow groove around the top instead of a shoulder — the line tightens around the groove.',
      'Add a 45° angle to the top so a mallet hits cleanly.',
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/7C23P5UwTX4',
      title: 'Bushcraft Basics: How To Make A Tent Stake',
    },
  },
  {
    slug: 'decorative-notches',
    category: 'woodcarving',
    title: 'Decorative Notches',
    tagline: 'A stop-cut + a chip cut. Three patterns to practice on.',
    difficulty: 'Intermediate',
    timeRequired: '15–20 minutes',
    useCases: ['Personalizing a walking stick', 'Marking grip points', 'Quiet creative time at camp'],
    outcome: 'Clean, uniform decorative notches around a stick or wooden handle.',
    materials: ['A bark-free, sanded stick or handle', 'A camp knife', 'A pencil for marking (optional)'],
    steps: [
      'Mark the notch positions lightly with a pencil. Even spacing matters more than perfect placement.',
      'Make the first stop-cut: hold the blade perpendicular to the stick at one edge of the notch and press straight in, about ⅛ inch deep.',
      'From the opposite side of the notch, angle the blade at about 30° toward the stop-cut and take a thin push cut. The chip should pop free against the stop-cut.',
      'If the chip doesn’t pop free, deepen the stop-cut and try again — don’t force the angle cut.',
      'Repeat the stop-cut/angle-cut pattern around the stick at each pencil mark.',
      'Smooth any ragged edges with a very light pull cut (thumb-assist).',
    ],
    proTips: [
      'Three patterns to start with: a single ring (one notch row), a chevron (alternating angles around the circumference), and a spiral (notches that move down the stick).',
      'Notches catch dirt over time — that’s the point. They’ll darken into the wood.',
    ],
    commonMistakes: [
      'Skipping the stop-cut and going straight to angle cuts — chips tear and notches look ragged.',
      'Cutting too deep on the stop-cut. ⅛ inch is plenty for visible texture.',
    ],
    safetyNotes: [
      'Stop-cuts press straight in. Don’t rock the blade — it can pop off and slip.',
      'Carve on a stable surface; never on your thigh.',
    ],
    safetyTone: 'critical',
    variations: [
      'Stained notches: rub charcoal from the fire into the cuts for sharp dark lines.',
      'Date and trip notches: one notch per camping trip, dated below.',
    ],
    videoEmbed: {
      url: 'https://www.youtube-nocookie.com/embed/XQVX7BzlldY',
      title: 'Whittling: How to Make a Stop Cut',
    },
  },
]
