import type { Activity } from './types'

export const ACTIVITIES: Activity[] = [
  {
    slug: 'two-truths-and-a-trail',
    title: 'Two Truths and a Trail',
    tagline: 'A camp-flavored icebreaker that warms up a new group fast.',
    category: 'icebreaker',
    ageRange: 'all-ages',
    groupSize: '5-10',
    energyLevel: 'low',
    timeRequired: '5-10min',
    setupDifficulty: 'none',
    vibe: 'calm',
    materials: ['Nothing — just a circle of people'],
    instructions: [
      'Sit in a circle around the picnic table or fire ring.',
      'Each person shares three statements about themselves: two true and one false. At least one statement should be camp- or outdoor-related (e.g. "I have hiked a 14er").',
      'The group votes on which statement is the lie.',
      'The speaker reveals the lie. Move to the next person clockwise.',
    ],
    winCondition: 'Everyone has gone, and the group has learned something new about each member.',
    variations: [
      'Camp edition: all three statements must be about prior camping or outdoor experiences.',
      'Kid mode: two statements, one true and one false. Easier for younger players.',
      'Silent vote: hold up fingers (1, 2, or 3) for the lie instead of calling out.',
    ],
    safetyNotes: [],
    recommendedFor: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'campfire-story-chain',
    title: 'Campfire Story Chain',
    tagline: 'A collaborative story built one sentence at a time.',
    category: 'campfire',
    ageRange: 'all-ages',
    groupSize: '5-10',
    energyLevel: 'low',
    timeRequired: '15-30min',
    setupDifficulty: 'none',
    vibe: 'calm',
    materials: ['A campfire (or lantern) and a circle of seats'],
    instructions: [
      'Pick a starter — usually the youngest, or whoever has the marshmallow stick.',
      'The starter says one sentence to begin a story. ("It was the third night of the trip when we noticed the lights.")',
      'Each player adds one sentence, going around the circle.',
      'No vetoing — every contribution stays. Keep it kid-friendly.',
      'End the story when it reaches a natural close, or after three full laps of the circle.',
    ],
    winCondition: 'The group lands on an ending everyone agrees feels right.',
    variations: [
      'Word at a time: each person adds only one word. Much harder, much funnier.',
      'Genre pick: vote on a genre first (mystery, comedy, adventure).',
      'Photo round: at the end, pick the most memorable line and write it down for later.',
    ],
    safetyNotes: ['Keep stories age-appropriate when younger kids are present.'],
    recommendedFor: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'flashlight-tag',
    title: 'Flashlight Tag',
    tagline: 'Hide-and-seek after dark — the camp classic.',
    category: 'night',
    ageRange: '9-12',
    groupSize: '5-10',
    energyLevel: 'high',
    timeRequired: '15-30min',
    setupDifficulty: 'none',
    vibe: 'competitive',
    materials: ['One flashlight per player', 'A defined play area with clear boundaries'],
    instructions: [
      'Walk the play boundary together before starting. Identify hard limits — fire ring, road, water.',
      'Pick one player as "It." It counts to 30 with eyes closed.',
      'Everyone else hides within the boundary. Flashlights stay off while hiding.',
      'It hunts with their flashlight on. If the beam lands on a hider and It calls their name, that hider is tagged.',
      'Tagged players become hunters too. Game ends when everyone is tagged.',
    ],
    winCondition: 'The last untagged hider wins and is It next round.',
    variations: [
      'Sardines: one person hides, the rest hunt. When you find the hider, you join them silently.',
      'Glow-stick edition: each hider must wear a glow stick visible from one angle only.',
      'Time limit: 10 minutes per round. Anyone untagged at the buzzer wins.',
    ],
    safetyNotes: [
      'Walk the boundary together before lights-out so everyone knows the limits.',
      'No hiding in trees, water, or anywhere requiring climbing.',
      'Each player keeps a flashlight on them at all times — even when hiding — for emergencies.',
    ],
    recommendedFor: ['first-night-camp', 'first-weekend-camp'],
  },
  {
    slug: 'glow-stick-ring-toss',
    title: 'Glow Stick Ring Toss',
    tagline: 'Lawn-game energy in the dark, with built-in spectacle.',
    category: 'night',
    ageRange: '6-8',
    groupSize: '2-4',
    energyLevel: 'medium',
    timeRequired: '15-30min',
    setupDifficulty: 'minimal',
    vibe: 'competitive',
    materials: [
      'A pack of glow-stick necklaces (8–12)',
      'Three short stakes or sticks driven into the ground 6–10 feet away',
    ],
    instructions: [
      'Activate all glow sticks and connect into rings using their connector caps.',
      'Drive three stakes into the ground at staggered distances. The far stake is worth more points.',
      'Each player gets 4 rings per turn.',
      'Standing behind a marked toss line, players toss rings at the stakes.',
      'Score: 1 point near, 2 points middle, 3 points far. First to 11 wins.',
    ],
    winCondition: 'First player to 11 points wins.',
    variations: [
      'Team mode: pairs alternate tosses, share a score.',
      'Glow horseshoes: substitute glow rings for horseshoe rules if you have stakes.',
      'Timed round: 90 seconds per player, total points scored.',
    ],
    safetyNotes: [
      'Do not toss toward the campfire or the tent.',
      'Glow sticks contain a non-toxic but bitter fluid. Discard any cracked rings; do not let young kids chew on them.',
    ],
    recommendedFor: ['backyard-test', 'first-night-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'capture-the-flag',
    title: 'Capture the Flag',
    tagline: 'The original team game, scaled to a campsite.',
    category: 'team',
    ageRange: '9-12',
    groupSize: '10+',
    energyLevel: 'high',
    timeRequired: '30-60min',
    setupDifficulty: 'minimal',
    vibe: 'competitive',
    materials: [
      'Two bandanas, towels, or shirts (one per team) to act as flags',
      'A play area large enough to split in half with a clear midline (a trail, a row of stakes)',
    ],
    instructions: [
      'Split into two teams. Each team picks a "home" half of the field and a flag location visible to the other team.',
      'Mark a clear midline. No tagging happens on your own side.',
      'On "go," players cross the midline to grab the other team\'s flag.',
      'If you are tagged on the opposing side, you go to "jail" — a designated spot near their flag — until a teammate frees you.',
      'A team wins by carrying the opposing flag back across the midline without being tagged.',
    ],
    winCondition: 'Carry the opposing team\'s flag across the midline to your home side.',
    variations: [
      'Three-flag chaos: each team plants three flags. First to capture all three wins.',
      'Glow edition: play after dark with glow-stick flags.',
      'Time-limited: most flag captures in 20 minutes wins.',
    ],
    safetyNotes: [
      'Set boundaries that exclude fire rings, water, and parking areas.',
      'No diving tags. Two-handed touch only.',
      'Pause for a head count every 15 minutes if the play area is wooded.',
    ],
    recommendedFor: ['first-weekend-camp'],
  },
  {
    slug: 'camp-olympics',
    title: 'Camp Olympics',
    tagline: 'A multi-event tournament that fills an afternoon.',
    category: 'team',
    ageRange: 'all-ages',
    groupSize: '10+',
    energyLevel: 'high',
    timeRequired: '1hour+',
    setupDifficulty: 'moderate',
    vibe: 'competitive',
    materials: [
      'A score sheet and pen',
      '4–6 small props depending on events: rope, balls, buckets, sticks',
      'Optional: medals or ribbons for the top three',
    ],
    instructions: [
      'Pick 4–6 short events. Suggested: tug-of-war, three-legged race, stick toss for distance, water-bucket relay, scavenger sprint, balance walk.',
      'Split players into teams of 3–5. Teams pick names.',
      'Run each event one at a time. Score 5 points for first, 3 for second, 1 for third.',
      'Track scores on the sheet. Announce running totals between events.',
      'After the last event, the team with the most total points wins.',
    ],
    winCondition: 'Team with the highest total score after all events wins.',
    variations: [
      'Family teams: split by family unit instead of mixed teams.',
      'Junior division: kids-only events with adult coaches.',
      'Awards ceremony: hand out playful titles ("Most Mud Earned") to every team member.',
    ],
    safetyNotes: [
      'Match event difficulty to the youngest player.',
      'Have water available; pause between events for hydration.',
      'Run any race events on flat ground away from fire rings and tent stakes.',
    ],
    recommendedFor: ['first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'silent-line-up-challenge',
    title: 'Silent Line-Up Challenge',
    tagline: 'A team puzzle that builds communication without words.',
    category: 'team',
    ageRange: '9-12',
    groupSize: '5-10',
    energyLevel: 'medium',
    timeRequired: '5-10min',
    setupDifficulty: 'none',
    vibe: 'calm',
    materials: ['Open ground for the group to stand on'],
    instructions: [
      'Pick a sorting rule. Examples: tallest to shortest, by birthday month, by length of hair.',
      'Tell the group the rule, then say "go." From this moment, no one can speak.',
      'The group must arrange themselves into a single line that satisfies the rule, using only gestures, eye contact, and pointing.',
      'When the group thinks they are sorted, they raise both hands. Check the line.',
      'Run a second round with a harder rule: shoe size, distance from home, last digit of phone number.',
    ],
    winCondition: 'The group sorts itself correctly without anyone speaking.',
    variations: [
      'Eyes closed: sort by birthday, fully blindfolded. (Use a spotter for tripping hazards.)',
      'Whisper edition: light talking allowed, but only at a whisper.',
      'Mixed-team races: two teams race to sort first.',
    ],
    safetyNotes: ['Run on flat, open ground. Look out for tent stakes and roots.'],
    recommendedFor: ['first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'rock-skipping-contest',
    title: 'Rock Skipping Contest',
    tagline: 'A simple competition that takes ten minutes and feels timeless.',
    category: 'movement',
    ageRange: '9-12',
    groupSize: '2-4',
    energyLevel: 'medium',
    timeRequired: '15-30min',
    setupDifficulty: 'none',
    vibe: 'competitive',
    materials: ['A flat-water pond, lake, or slow river', 'Flat skipping stones (everyone hunts their own)'],
    instructions: [
      'Spend 5 minutes hunting flat, palm-sized stones from the shore.',
      'Each player takes turns throwing one stone, sidearm and low, across the water.',
      'Count the skips out loud. A skip = one bounce off the water surface.',
      'Each player gets three throws per round. Best single throw counts.',
      'Run three rounds. Highest single skip count across all rounds wins.',
    ],
    winCondition: 'Highest skip count from a single throw wins.',
    variations: [
      'Distance contest: instead of skips, measure how far the stone goes.',
      'Trick shots: bonus points for skips that curve or land in a target zone.',
      'Family relay: each family member gets one throw; total skips per family.',
    ],
    safetyNotes: [
      'Check the throwing line is clear behind you — backswings have hit kids and adults.',
      'Do not throw near swimmers, fishing lines, or boats.',
    ],
    recommendedFor: ['first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'nature-scavenger-hunt',
    title: 'Nature Scavenger Hunt',
    tagline: 'A printable list that turns a walk into a mission.',
    category: 'exploration',
    ageRange: '6-8',
    groupSize: '2-4',
    energyLevel: 'medium',
    timeRequired: '30-60min',
    setupDifficulty: 'minimal',
    vibe: 'exploration',
    materials: [
      'A scavenger list per kid (handwritten or printed)',
      'A small bag for collected items',
      'A pencil',
    ],
    instructions: [
      'Write a list of 8–12 items kids can spot or collect. Examples: a feather, a smooth rock, a yellow leaf, an acorn, a Y-shaped stick, something soft, something rough.',
      'Add a few "look but don\'t collect" items: a spider web, a bird, an animal track.',
      'Set a clear boundary for the search and a return time.',
      'Send kids out in pairs. Adults shadow at a distance.',
      'Regroup at the picnic table. Each kid shares their finds and crosses items off the list.',
    ],
    winCondition: 'A kid completes the list — or finds the most items in the time window.',
    variations: [
      'Color hunt: find one item of every color of the rainbow.',
      'Texture hunt: rough, smooth, soft, scratchy, sticky.',
      'Camera version: photograph items instead of collecting (good for teens).',
    ],
    safetyNotes: [
      'Set boundaries kids can see from. Walk the perimeter together first.',
      'Tell kids what NOT to touch: shiny leaves of three (poison ivy), snakes, mushrooms, anything in water.',
      'Each pair carries a whistle. Three blasts = come back now.',
    ],
    recommendedFor: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'trail-bingo',
    title: 'Trail Bingo',
    tagline: 'A 5×5 grid that turns any trail into a hunt.',
    category: 'exploration',
    ageRange: '6-8',
    groupSize: '2-4',
    energyLevel: 'medium',
    timeRequired: '30-60min',
    setupDifficulty: 'minimal',
    vibe: 'exploration',
    materials: [
      'A 5×5 bingo card per kid (drawn at camp or printed at home)',
      'A pencil',
    ],
    instructions: [
      'Before the trail: each kid fills their grid with 25 items they might see — bird, mushroom, anthill, woodpecker hole, three different leaf shapes, a creek, etc.',
      'On the trail, kids cross out a square each time they spot one of their items.',
      'The first to mark five in a row (across, down, or diagonal) calls "bingo."',
      'Continue walking — they can keep playing for blackout (every square crossed off).',
    ],
    winCondition: 'First kid to mark five in a row calls bingo. Blackout is the bonus round.',
    variations: [
      'Adult mode: 7×7 grid with harder finds.',
      'Family card: one shared card, anyone can mark.',
      'Photo bingo: phone photos required for proof.',
    ],
    safetyNotes: ['Keep eyes up between marks — kids tend to walk while staring at the card.'],
    recommendedFor: ['first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'stick-shelter-build',
    title: 'Stick Shelter Build',
    tagline: 'A real survival skill kids feel proud of after.',
    category: 'creative',
    ageRange: '6-8',
    groupSize: '2-4',
    energyLevel: 'medium',
    timeRequired: '30-60min',
    setupDifficulty: 'none',
    vibe: 'creative',
    materials: [
      'Fallen sticks and branches (no breaking from live trees)',
      'A "ridge" — a downed log, a low fork between two trees, or a tightly-rigged guy line',
      'Optional: a tarp or emergency blanket for the final layer',
    ],
    instructions: [
      'Pick a ridge: a fallen log, a fork between trees, or a low rigged line. The ridge becomes the spine of the shelter.',
      'Lean long sticks against the ridge at an angle to form a frame on each side. Cover the full length.',
      'Layer shorter sticks across the frame to fill gaps.',
      'Pile leaves, pine needles, or grass on top — at least one foot thick — for weatherproofing.',
      'Add a tarp on top if available for actual rain protection.',
      'Crawl in. Time how long it takes for everyone inside to feel warmer.',
    ],
    winCondition: 'A kid can lie inside the shelter without seeing daylight through the roof.',
    variations: [
      'Race: two teams build side-by-side, judged on weather-readiness.',
      'Mini version: build a shelter big enough only for a stuffed animal.',
      'Survival add-on: place a flashlight inside and time how long the warmth holds.',
    ],
    safetyNotes: [
      'Only collect from the ground — never break branches off live trees.',
      'Avoid building under dead overhead branches ("widow makers").',
      'Disassemble the shelter before leaving the campsite. Leave no trace.',
    ],
    recommendedFor: ['first-night-camp', 'first-weekend-camp'],
  },
  {
    slug: 'stargazing-constellation-hunt',
    title: 'Stargazing Constellation Hunt',
    tagline: 'A wind-down activity that lands the day with awe.',
    category: 'wind-down',
    ageRange: 'all-ages',
    groupSize: '2-4',
    energyLevel: 'low',
    timeRequired: '15-30min',
    setupDifficulty: 'none',
    vibe: 'calm',
    materials: [
      'A sky chart or star app (Sky Guide, SkyView, Stellarium — download the offline maps before leaving cell coverage)',
      'A red flashlight or red filter on a headlamp to preserve night vision',
      'Optional: a blanket or sleeping pads to lie on',
    ],
    instructions: [
      'Walk away from any lit areas — even small camp lanterns wash out the sky.',
      'Lie on your backs. Take 5 minutes for eyes to adjust to the dark.',
      'Find the Big Dipper first — it is the easiest anchor.',
      'From the Big Dipper, trace the line through the two front-edge stars upward to find Polaris (the North Star).',
      'Use a sky chart or app to find one new constellation per night. Cassiopeia, Orion, and the Summer Triangle are great starters.',
    ],
    winCondition: 'Everyone can point to one new constellation by the end of the session.',
    variations: [
      'Meteor watch: lie still for 10 minutes during a known shower (Perseids in August, Geminids in December).',
      'Satellite spotting: track ISS pass-overs using a free app — visible to the naked eye.',
      'Story round: each constellation gets a one-sentence story made up by the group.',
    ],
    safetyNotes: [
      'Use a red flashlight only — white light wipes out 20 minutes of dark adaptation.',
      'Stay close to camp; do not wander to find darker sky after lights-out.',
    ],
    recommendedFor: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'trail-journal-sketching',
    title: 'Trail Journal Sketching',
    tagline: 'A solo activity for older kids and adults that slows the day down.',
    category: 'wind-down',
    ageRange: '13-17',
    groupSize: 'solo',
    energyLevel: 'low',
    timeRequired: '30-60min',
    setupDifficulty: 'minimal',
    vibe: 'creative',
    materials: [
      'A small notebook or sketchpad',
      'A pencil and a black pen',
      'Optional: a small set of colored pencils or watercolors',
    ],
    instructions: [
      'Find a spot alone — a log, a flat rock, the picnic table — within sight of camp.',
      'Set a 30-minute timer. Do not check it.',
      'Pick one subject: a tree, the fire pit, the view from your seat. Sketch it loosely. The goal is observation, not realism.',
      'Add three written notes: a sound you hear, a smell, a thought you want to remember.',
      'Date the page. That is the entry.',
    ],
    winCondition: 'A finished page in the journal — sketch plus notes.',
    variations: [
      'Two-page spread: left side sketch, right side full written entry.',
      'Group share: at the end, each person reads one note (not the sketch) aloud.',
      'Daily streak: same activity each evening of a multi-night trip — see how the entries evolve.',
    ],
    safetyNotes: [
      'Stay within shouting distance of camp.',
      'Pack out everything — including pencil shavings.',
    ],
    recommendedFor: ['first-weekend-camp', 'easy-family-basecamp'],
  },
]

  {
    slug: 'shadow-puppet-theatre',
    title: 'Shadow Puppet Theatre',
    tagline: 'Hand shadows on the tent wall — the original camp entertainment.',
    category: 'campfire',
    ageRange: '3-5',
    groupSize: '2-4',
    energyLevel: 'low',
    timeRequired: '15-30min',
    setupDifficulty: 'minimal',
    vibe: 'creative',
    materials: [
      'A bright lantern or flashlight placed on the ground inside or behind the tent',
      'A flat tent wall or a hung white sheet',
    ],
    instructions: [
      'Set a lantern or flashlight on the ground facing the tent wall. The higher the light, the sharper the shadows.',
      'Sit or kneel between the light and the wall. Hands held about a foot from the wall give the clearest shapes.',
      'Start with the basics: duck (index finger bent down, thumb out), rabbit (two fingers up, thumb holding the other two), dog (four fingers pressed together, thumb out).',
      'Once everyone has a character, improvise a short scene. The light-holder narrates.',
      'Pass the lantern to a new storyteller for the next scene.',
    ],
    winCondition: undefined,
    variations: [
      'Full body: stand farther back with a stronger light to cast full silhouettes against the tent.',
      'Story challenge: pick a fairy tale and act it out entirely in shadow.',
      'Audience guess: one person makes a shape, everyone else guesses what it is.',
    ],
    safetyNotes: [
      'Keep the lantern on the ground — never hang a hot lantern against a tent wall.',
      'Use an LED lantern only. No open-flame lanterns inside or against tents.',
    ],
    recommendedFor: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'leaf-rubbings',
    title: 'Leaf Rubbings',
    tagline: 'Transfer the veins of a leaf onto paper in under five minutes.',
    category: 'creative',
    ageRange: '3-5',
    groupSize: '2-4',
    energyLevel: 'low',
    timeRequired: '15-30min',
    setupDifficulty: 'minimal',
    vibe: 'creative',
    materials: [
      'Thin printer paper or a journal page',
      'Crayons or colored pencils with the paper wrapper removed',
      'A flat, hard surface (a book, a clipboard, or the picnic table)',
      'Fresh leaves with visible veins — maple, oak, and fern work best',
    ],
    instructions: [
      'Collect 4–6 leaves of different shapes and sizes. Leaves still slightly flexible (not fully dried) give the best detail.',
      'Place a leaf vein-side up on the flat surface. Lay a sheet of paper on top.',
      'Hold the paper still with one hand. With the other, rub a crayon lengthwise across the paper over the leaf. Press firmly and evenly.',
      'Lift the paper to reveal the leaf print. Label it with the tree name if you know it.',
      'Fill a page with several rubbings. Compare the vein patterns.',
    ],
    winCondition: undefined,
    variations: [
      'ID challenge: look up the tree name for each rubbing using a field guide or app.',
      'Layered art: overlap three rubbings in different colors on the same page.',
      'Postcard: address the finished page to someone at home and mail it.',
    ],
    safetyNotes: [
      'Wash hands after handling unknown plants — some leaves cause skin irritation.',
      'Do not pull leaves from protected or rare plants. Collect from the ground if possible.',
    ],
    recommendedFor: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'rock-painting',
    title: 'Rock Painting',
    tagline: 'Paint a rock at camp, hide it on the trail for a stranger to find.',
    category: 'creative',
    ageRange: '6-8',
    groupSize: '2-4',
    energyLevel: 'low',
    timeRequired: '30-60min',
    setupDifficulty: 'minimal',
    vibe: 'creative',
    materials: [
      'Smooth, flat rocks (collect from the ground before the activity)',
      'Paint pens or acrylic paint with a small brush',
      'A cup of water for rinsing brushes',
      'A paper plate as a palette',
      'Optional: a clear coat spray or Mod Podge to seal finished rocks',
    ],
    instructions: [
      'Each person collects 2–3 smooth rocks from around camp. Flat, palm-sized rocks hold paint best.',
      'Rinse rocks and let them dry fully. Paint does not stick to wet stone.',
      'Sketch a loose design in pencil first if needed. Simple shapes work best: animals, geometric patterns, words, emojis.',
      'Apply paint in thin layers. Let each layer dry for 5 minutes before adding details.',
      'Sign the back with the date and campsite (optional). Seal with a clear coat if available.',
      'Hide your finished rocks somewhere visible on the trail or near a trailhead for others to find.',
    ],
    winCondition: undefined,
    variations: [
      'Rock swap: trade rocks with another camper at the trailhead.',
      'Camp markers: paint rocks to label gear areas or tent spots.',
      'Story rocks: each person paints a character; arrange them to tell a story around the fire.',
    ],
    safetyNotes: [
      'Only collect rocks from the ground — never remove rocks embedded in trails, stream beds, or protected areas.',
      'Use water-based, non-toxic paint around younger kids.',
      'Seal rocks before placing them outdoors so paint does not wash into water sources.',
    ],
    recommendedFor: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
  {
    slug: 'campfire-hot-seat',
    title: 'Campfire Hot Seat',
    tagline: 'One person in the chair, five rapid-fire questions — answers must be instant.',
    category: 'icebreaker',
    ageRange: 'all-ages',
    groupSize: '5-10',
    energyLevel: 'low',
    timeRequired: '15-30min',
    setupDifficulty: 'none',
    vibe: 'calm',
    materials: ['Nothing — just seats around the fire'],
    instructions: [
      'One person sits in the "hot seat" — the chair closest to the fire, or just a designated spot.',
      'The group takes turns asking questions. The hot seat must answer immediately — no pausing to think.',
      'Keep questions light and camp-flavored: "Best thing about today?", "What would your camp name be?", "What scared you as a kid?", "Tent or hammock?"',
      'After five questions, the hot-seat player picks the next person.',
      'No skipping questions. If the answer is "I don\'t know," that counts — the group decides if it\'s valid.',
    ],
    winCondition: undefined,
    variations: [
      'Would you rather: every question is a would-you-rather. ("Eat only trail mix for a week, or sleep in the rain every night?")',
      'Theme rounds: all questions must be about camping, food, or childhood memories.',
      'All-in: everyone answers the same question simultaneously — call it out on three.',
    ],
    safetyNotes: ['Keep questions inclusive and appropriate for the youngest player present.'],
    recommendedFor: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
  },
]

export function getActivityBySlug(slug: string): Activity | null {
  return ACTIVITIES.find((a) => a.slug === slug) ?? null
}
