import type { AffiliateProduct, PlanSlug } from '@/types'

export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  // ------------------------------------------------------------------
  // Shared — used by backyard-test, first-night-camp, easy-family-basecamp.
  // (first-weekend-camp has its own curated list further down.)
  // ------------------------------------------------------------------
  {
    id: 'tent-sundome-3',
    name: 'Coleman Sundome 3-Person Tent',
    description: 'The couple or solo-with-gear pick. 7×7 ft floor, sets up in 10 minutes, fits a full-size air bed.',
    amazonAsin: 'B004J2GUOK',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/f19b70cc-14ac-46ae-bec2-33b25b7fd2a9.__CR0,0,1464,600_PT0_SX1464_V1___.png',
    category: 'essential',
    templateSlugs: ['first-night-camp'],
    priceRange: '~$90',
  },
  {
    id: 'tent-sundome-6',
    name: 'Coleman Sundome 6-Person Tent',
    description: 'The size-up pick for families of 5+ or anyone who wants room to stand and spread out gear. 10×10 ft floor.',
    amazonAsin: 'B004E4AWYA',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/f19b70cc-14ac-46ae-bec2-33b25b7fd2a9.__CR0,0,1464,600_PT0_SX1464_V1___.png',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '~$160',
  },
  {
    id: 'sleeping-bag-family',
    name: 'Kelty Tuck 20 Sleeping Bag',
    description: 'Rated to 20°F, roomy fit, easy to get into. Works for most 3-season family trips.',
    amazonAsin: 'B07H99CMNP',
    affiliateUrl: 'https://amzn.to/4mVpMom',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media/vc/94b627ff-60b3-4f09-af91-225e2a7b114d._CR0,0,970,300_PT0_SX970__.jpg',
    category: 'essential',
    templateSlugs: ['first-night-camp'],
    priceRange: '~$95',
  },
  {
    id: 'sleeping-pad-air',
    name: 'TETON Sports ComfortLite Sleeping Pad',
    description: 'Self-inflating, comfortable, packs small. Real comfort upgrade over foam.',
    amazonAsin: 'B00HC9QTO8',
    affiliateUrl: 'https://amzn.to/4vG4xdY',
    imageUrl: 'https://m.media-amazon.com/images/I/71AVJB+xn6L._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: [],
    priceRange: '~$75',
  },
  {
    id: 'air-mattress-queen',
    name: 'SoundAsleep Dream Series Air Mattress',
    description: 'Queen size, built-in pump, stays inflated all night. The right call for comfort-focused family trips.',
    amazonAsin: 'B00FAW4O0A',
    affiliateUrl: 'https://amzn.to/4vLAkKN',
    imageUrl: 'https://m.media-amazon.com/images/I/616X+781lOL._AC_SX679_.jpg',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '~$120',
  },
  {
    id: 'stove-2-burner',
    name: 'Camp Chef Everest 2X 2-Burner Stove',
    description: '40,000 BTU, wind-resistant, matchless ignition. Cooks real meals, not just boiling water.',
    amazonAsin: 'B09KNVRDNQ',
    affiliateUrl: 'https://amzn.to/4sQx6Tz',
    imageUrl: 'https://m.media-amazon.com/images/I/71J5ttHnYvL._AC_SX679_.jpg',
    category: 'essential',
    templateSlugs: ['first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '~$210',
  },
  {
    id: 'headlamp-family',
    name: 'Black Diamond Spot 400 Headlamp',
    description: '400 lumens, red night mode, waterproof. One per person is non-negotiable.',
    amazonAsin: 'B09NQK2581',
    affiliateUrl: 'https://amzn.to/4mXLRTe',
    imageUrl: 'https://m.media-amazon.com/images/I/81sGcNXb1eL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['backyard-test'],
    priceRange: '~$50',
  },
  {
    id: 'camp-chairs',
    name: 'ALPS Mountaineering Leisure Chair',
    description: 'Sturdy steel frame, 300 lb capacity, cup holder. The chair you actually want to sit in for an evening.',
    amazonAsin: 'B001LF3FZK',
    affiliateUrl: 'https://amzn.to/4sVHJEv',
    imageUrl: 'https://m.media-amazon.com/images/I/61B-kRUS-IL._AC_SL1200_.jpg',
    category: 'comfort',
    templateSlugs: [],
    priceRange: '~$95',
  },
  {
    id: 'cooler-basic',
    name: 'Coleman 54-Quart Steel-Belted Cooler',
    description: 'Keeps ice up to 4 days, 85-can capacity, Have-A-Seat lid. Classic for good reason.',
    amazonAsin: 'B0009PURKE',
    affiliateUrl: 'https://amzn.to/4sQx6Tz',
    imageUrl: 'https://m.media-amazon.com/images/I/91uqAgVltVS._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: [],
    priceRange: '~$120',
  },
  {
    id: 'canopy-camp',
    name: 'CORE 10x10 Instant Pop-Up Canopy',
    description: 'Sets up in 2 minutes. Shade at camp is a comfort multiplier.',
    amazonAsin: 'B01E45EYJY',
    affiliateUrl: 'https://amzn.to/4cOwo3a',
    imageUrl: 'https://m.media-amazon.com/images/I/610Y31VdNIL._AC_.jpg',
    category: 'convenience',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '~$130',
  },

  // ------------------------------------------------------------------
  // FIRST WEEKEND CAMP — curated list from the affiliate sheet.
  // Uses explicit amzn.to short links (affiliateUrl) so commission
  // attribution stays on the user's Associates account.
  // ------------------------------------------------------------------
  {
    id: 'fwc-tent-sundome',
    name: 'Coleman Sundome 4-Person Tent',
    description: 'Best-selling family dome tent. 9×7 ft floor, weatherproof, quick to pitch, fits a queen air bed. The safe first-trip tent.',
    amazonAsin: 'B0D7QHY574',
    affiliateUrl: 'https://amzn.to/4sUKHJs',
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/B0D7QHY574.01.L.jpg',
    category: 'essential',
    templateSlugs: ['first-weekend-camp'],
    priceRange: '~$116',
  },
  {
    id: 'fwc-stove-coleman-1burner',
    name: 'Coleman 1-Burner Propane Stove',
    description: 'Single burner, propane, rock-solid reliability. Boils water fast and handles a skillet.',
    amazonAsin: 'B0009PUR5E',
    affiliateUrl: 'https://amzn.to/4uc7DVG',
    imageUrl: 'https://m.media-amazon.com/images/I/81aj95-ouRL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: [],
    priceRange: '~$40',
  },
  {
    id: 'fwc-cooler-rolling',
    name: 'Coleman Classic Rolling Cooler',
    description: 'Insulated rolling cooler with telescoping handle. Makes the load-in from the car a non-issue.',
    amazonAsin: 'B07N3C6Y5M',
    affiliateUrl: 'https://amzn.to/4d3oHXX',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/6a95b9ce-ba2f-46da-a5f8-82593670f6eb.__CR0,0,1464,600_PT0_SX1464_V1___.png',
    category: 'essential',
    templateSlugs: ['first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '~$107',
  },
  {
    id: 'fwc-cot-airbed-combo',
    name: 'Coleman Queen Airbed Cot Combo',
    description: 'Folding steel cot with queen air mattress on top. Gets you off the ground with real comfort.',
    amazonAsin: 'B00AU6AVLW',
    affiliateUrl: 'https://amzn.to/4ut42CT',
    imageUrl: 'https://m.media-amazon.com/images/I/91+ezTNiVbL._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: [],
    priceRange: '~$30',
  },
  {
    id: 'fwc-lantern-consciot',
    name: 'Consciot LED Camping Lantern (2-pack)',
    description: 'Battery-powered, collapsible, bright enough for the picnic table. Two is the right number.',
    amazonAsin: 'B08D6X8F1L',
    affiliateUrl: 'https://amzn.to/4tz86RT',
    imageUrl: 'https://m.media-amazon.com/images/I/71ATGzY0CUL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp'],
    priceRange: '~$30',
  },
  {
    id: 'fwc-sleeping-bag-mallome',
    name: 'MalloMe Sleeping Bag',
    description: 'Lightweight 3-season bag. Affordable, easy to wash, comfortable for a weekend.',
    amazonAsin: 'B077XQDZW4',
    affiliateUrl: 'https://amzn.to/4cKiwH7',
    imageUrl: 'https://m.media-amazon.com/images/I/71dhzPLdNML._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['first-weekend-camp'],
    priceRange: '~$26',
  },
  {
    id: 'fwc-chair-gci-rocker',
    name: 'GCI Outdoor Freestyle Rocker',
    description: 'Camp chair that actually rocks. The upgrade you’ll thank yourself for around the fire.',
    amazonAsin: 'B00D4JYR62',
    affiliateUrl: 'https://amzn.to/4e8dK8O',
    imageUrl: 'https://m.media-amazon.com/images/I/71O4-VrNP3L._AC_SL1000_.jpg',
    category: 'comfort',
    templateSlugs: ['first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '~$80',
  },
  {
    id: 'fwc-projector-tmy',
    name: 'TMY 1080P Mini Projector',
    description: 'Portable Bluetooth projector. Movie night on the side of the tent — an unfair advantage with kids.',
    amazonAsin: 'B082F13J55',
    affiliateUrl: 'https://amzn.to/3OlFWKU',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/bb0c1152-f522-4772-98ea-c3cac62e88bf.__CR0,0,1464,600_PT0_SX1464_V1___.jpg',
    category: 'convenience',
    templateSlugs: [],
    priceRange: '~$50',
  },
  {
    id: 'fwc-trash-can-wakeman',
    name: 'Wakeman Outdoor Collapsible Trash Can',
    description: 'Folds flat, pops open at camp. Keeps the site tidy and critter-resistant.',
    amazonAsin: 'B0CHKGXSQ6',
    affiliateUrl: 'https://amzn.to/4cHYL2S',
    imageUrl: 'https://m.media-amazon.com/images/I/913OeuUhboL._AC_SL1500_.jpg',
    category: 'convenience',
    templateSlugs: [],
    priceRange: '~$21',
  },
  {
    id: 'fwc-lantern-hanger',
    name: 'Coleman Lantern Hanger',
    description: 'Clamp-on hanger for a tent pole or tree branch. A $20 quality-of-life upgrade at night.',
    amazonAsin: 'B0009PUTJI',
    affiliateUrl: 'https://amzn.to/3Qm3Mqu',
    imageUrl: 'https://m.media-amazon.com/images/I/81IPjzQWjlL.jpg',
    category: 'convenience',
    templateSlugs: ['first-night-camp'],
    priceRange: '~$20',
  },
]

export function getProductsForTemplate(slug: PlanSlug): AffiliateProduct[] {
  return AFFILIATE_PRODUCTS.filter((p) => p.templateSlugs.includes(slug))
}
