import type { AffiliateProduct, PlanSlug } from '@/types'

export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  {
    id: 'tent-family',
    name: 'Coleman Sundome 4-Person Tent',
    description: 'Best-selling family dome tent. Sets up in 10 minutes, fits a queen air bed, rainfly included.',
    amazonAsin: 'B004J2GUOU',
    imageUrl: 'https://m.media-amazon.com/images/I/71vDvANrwuL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp'],
    priceRange: '$80–120',
  },
  {
    id: 'tent-basic',
    name: 'Coleman Sundome 2-Person Tent',
    description: 'Simple, reliable starter tent. Great for a backyard test or solo sleepout — a kid could set it up.',
    amazonAsin: 'B0D6FVR2BX',
    imageUrl: 'https://m.media-amazon.com/images/I/81YCm1N9hBL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['backyard-test'],
    priceRange: '$50–80',
  },
  {
    id: 'tent-cabin',
    name: 'Coleman Skydome 4-Person Tent',
    description: 'Near-vertical walls, 5-minute setup, fits a queen air mattress. Built for comfort.',
    amazonAsin: 'B07XC97D2X',
    imageUrl: 'https://m.media-amazon.com/images/I/81cApxg4HBL._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '$150–220',
  },
  {
    id: 'sleeping-bag-family',
    name: 'Kelty Tuck 20 Sleeping Bag',
    description: 'Rated to 20°F, roomy fit, easy to get into. Works for most 3-season family trips.',
    amazonAsin: 'B07H99CMNP',
    imageUrl: 'https://m.media-amazon.com/images/I/71Ae1HRqxoL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['backyard-test', 'first-night-camp', 'first-weekend-camp'],
    priceRange: '$80–120',
  },
  {
    id: 'sleeping-pad-air',
    name: 'TETON Sports ComfortLite Sleeping Pad',
    description: 'Self-inflating, comfortable, packs small. Real comfort upgrade over foam.',
    amazonAsin: 'B00HC9QTO8',
    imageUrl: 'https://m.media-amazon.com/images/I/71V8XpMxoVL._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: ['first-night-camp', 'first-weekend-camp'],
    priceRange: '$60–100',
  },
  {
    id: 'air-mattress-queen',
    name: 'SoundAsleep Dream Series Air Mattress',
    description: 'Queen size, built-in pump, stays inflated all night. The right call for comfort-focused family trips.',
    amazonAsin: 'B00FAW4O0A',
    imageUrl: 'https://m.media-amazon.com/images/I/81MgJHmanEL._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '$100–150',
  },
  {
    id: 'stove-2-burner',
    name: 'Camp Chef Everest 2X 2-Burner Stove',
    description: '40,000 BTU, wind-resistant, matchless ignition. Cooks real meals, not just boiling water.',
    amazonAsin: 'B09KNVRDNQ',
    imageUrl: 'https://m.media-amazon.com/images/I/81y1ki2xqOL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$150–200',
  },
  {
    id: 'headlamp-family',
    name: 'Black Diamond Spot 400 Headlamp',
    description: '400 lumens, red night mode, waterproof. One per person is non-negotiable.',
    amazonAsin: 'B09NQK2581',
    imageUrl: 'https://m.media-amazon.com/images/I/61RPg-QgHZL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$45–55',
  },
  {
    id: 'camp-chairs',
    name: 'ALPS Mountaineering Leisure Chair',
    description: 'Sturdy steel frame, 300 lb capacity, cup holder. The chair you actually want to sit in for an evening.',
    amazonAsin: 'B001LF3FZK',
    imageUrl: 'https://m.media-amazon.com/images/I/71pvdkG3-ML._AC_SL1500_.jpg',
    category: 'comfort',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$45–65',
  },
  {
    id: 'cooler-basic',
    name: 'Coleman 54-Quart Steel-Belted Cooler',
    description: 'Keeps ice up to 4 days, 85-can capacity, Have-A-Seat lid. Classic for good reason.',
    amazonAsin: 'B0009PURKE',
    imageUrl: 'https://m.media-amazon.com/images/I/71ra+7Of9IL._AC_SL1500_.jpg',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$120–180',
  },
  {
    id: 'canopy-camp',
    name: 'CORE 10x10 Instant Pop-Up Canopy',
    description: 'Sets up in 2 minutes. Shade at camp is a comfort multiplier.',
    amazonAsin: 'B01E45EYJY',
    imageUrl: 'https://m.media-amazon.com/images/I/81dqWUwvJML._AC_SL1500_.jpg',
    category: 'convenience',
    templateSlugs: ['first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$120–180',
  },
]

export function getProductsForTemplate(slug: PlanSlug): AffiliateProduct[] {
  return AFFILIATE_PRODUCTS.filter((p) => p.templateSlugs.includes(slug))
}
