import type { AffiliateProduct, PlanSlug } from '@/types'

export const AFFILIATE_PRODUCTS: AffiliateProduct[] = [
  {
    id: 'tent-family',
    name: 'REI Co-op Base Camp 4 Tent',
    description: 'Roomy 4-person tent with excellent weather protection. Sets up in under 15 minutes.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/tent-family/400/300',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp'],
    priceRange: '$300–400',
  },
  {
    id: 'tent-basic',
    name: 'REI Co-op Passage 2 Tent',
    description: 'Lightweight, reliable starter tent. Great for a backyard test or solo sleepout.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/tent-basic/400/300',
    category: 'essential',
    templateSlugs: ['backyard-test'],
    priceRange: '$150–200',
  },
  {
    id: 'tent-cabin',
    name: 'Coleman Skydome Camping Tent',
    description: 'Near-vertical walls, easy setup, fits a queen air mattress. Built for comfort.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/tent-cabin/400/300',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '$200–280',
  },
  {
    id: 'sleeping-bag-family',
    name: 'Kelty Tuck 20 Sleeping Bag',
    description: 'Rated to 20°F, roomy fit, easy to get into. Works for most 3-season family trips.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/sleeping-bag/400/300',
    category: 'essential',
    templateSlugs: ['backyard-test', 'first-night-camp', 'first-weekend-camp'],
    priceRange: '$80–120',
  },
  {
    id: 'sleeping-pad-air',
    name: 'REI Co-op Camp Dreamer Sleeping Pad',
    description: 'Self-inflating, comfortable, packs small. Genuine comfort upgrade over foam.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/sleeping-pad/400/300',
    category: 'comfort',
    templateSlugs: ['first-night-camp', 'first-weekend-camp'],
    priceRange: '$80–130',
  },
  {
    id: 'air-mattress-queen',
    name: 'SoundAsleep Dream Series Air Mattress',
    description: 'Queen size, stays inflated all night. The right call for a comfort-focused family trip.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/air-mattress/400/300',
    category: 'comfort',
    templateSlugs: ['easy-family-basecamp'],
    priceRange: '$100–150',
  },
  {
    id: 'stove-2-burner',
    name: 'Camp Chef Everest 2-Burner Stove',
    description: 'High-output, wind-resistant. Cooks real meals, not just boiling water.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/camp-stove/400/300',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$90–130',
  },
  {
    id: 'headlamp-family',
    name: 'Black Diamond Spot 400 Headlamp',
    description: '400 lumens, red night mode, comfortable strap. One per person is non-negotiable.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/headlamp/400/300',
    category: 'essential',
    templateSlugs: ['backyard-test', 'first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$35–50',
  },
  {
    id: 'camp-chairs',
    name: 'ALPS Mountaineering Leisure Chair',
    description: 'Sturdy, comfortable, easy to carry. The chair you actually want to sit in for an evening.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/camp-chairs/400/300',
    category: 'comfort',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$40–60',
  },
  {
    id: 'cooler-basic',
    name: 'Coleman 54-Quart Steel-Belted Cooler',
    description: 'Keeps ice 4–5 days, holds enough for a family weekend. Classic for good reason.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/cooler/400/300',
    category: 'essential',
    templateSlugs: ['first-night-camp', 'first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$100–160',
  },
  {
    id: 'canopy-camp',
    name: 'CORE 10x10 Instant Canopy',
    description: 'Sets up in 60 seconds. Shade at camp is a comfort multiplier.',
    affiliateUrl: '#',
    imageUrl: 'https://picsum.photos/seed/canopy/400/300',
    category: 'convenience',
    templateSlugs: ['first-weekend-camp', 'easy-family-basecamp'],
    priceRange: '$80–120',
  },
]

export function getProductsForTemplate(slug: PlanSlug): AffiliateProduct[] {
  return AFFILIATE_PRODUCTS.filter((p) => p.templateSlugs.includes(slug))
}
